### ISSUE TITLE
Many2Many cache bug.

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm/avaje-ebeanorm#227]
I'm using the newest eBean from maven 4.5.2.

I have entity with uses 2x many to many connection:
```java
 @Entity
 public class UserGroup implements UserGroupModel {
	@ManyToMany(cascade={CascadeType.REFRESH, CascadeType.PERSIST})
	@JoinTable(name="users_to_groups", joinColumns={@JoinColumn(name="group_id")}, inverseJoinColumns={@JoinColumn(name="user_id")})
	private Set<User> users = new HashSet<>();

	@ManyToMany(cascade={CascadeType.REFRESH, CascadeType.PERSIST})
	@JoinTable(name="subusers_to_groups", joinColumns={@JoinColumn(name="group_id")}, inverseJoinColumns={@JoinColumn(name="user_id")})
	private Set<User> subordinateUsers=new HashSet<>();
 }

@Entity(name="users")
public class User implements UserModel {
...
}
```
And the test is:
```java
	@Test
	public void testGroupSubordinates() {
		User manager = userDA.createNewUser(RandomStringUtils.randomAlphabetic(5));
		
		User sub1 = userDA.createNewUser(RandomStringUtils.randomAlphabetic(5));
		User sub2 = userDA.createNewUser(RandomStringUtils.randomAlphabetic(5));

		groupDA.modifyManyToMany(g, g.getUsers(), UserGroup.USERS, new User[] { manager }, null);
		assertEquals(0, g.getSubordinateUsers().size());

        }
```
And this fails - getSubordinateUsers()==1
But if I force refresh:
```java
		db.refreshMany(g, UserGroup.SUBORDINATEUSERS);
		assertEquals(0, g.getSubordinateUsers().size());
```
Then this is correct.

Method modifyManyToMany is:
```java
	public <M extends HasId> void modifyManyToMany(T entity, Collection<M> mapping, String propertyName, M[] toAdd, M[] toRemove) {
		modifyManyToMany(entity, mapping, propertyName, toAdd == null ? null : Arrays.asList(toAdd), toRemove == null ? null : Arrays.asList(toRemove));
	}

	public <M extends HasId> void modifyManyToMany(T entity, Collection<M> mapping, String propertyName, Collection<M> toAdd, Collection<M> toRemove) {
toAdd, toRemove);
		if (toAdd != null) {
			for (M hasId : toAdd) {
				mapping.add(hasId);
			}
		}
		
		if (toRemove != null) {
			for (M hasId : toRemove) {
				if (!mapping.remove(hasId)) {
					log.e("entity: %s must implement hashCode and equals methods! (or parent entity manyToMany mapping was not refreshed)", entity);
				}
			}
		}
		
		update(entity);
		refreshMany(entity, propertyName);
	}
```

It seems that cache is working for type UserGroup -> User - field users
and the same cache is used for UserGroup -> User - field subordinateUsers.

I wanted to write complete test for ebean sources (git master), but I cannot start it from maven:
```bash
export JAVA_HOME=/home/rysiek/workspace-documaster/jdk1.8.0_25/jre
mvn clean test
```
ends with:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE!
Running com.avaje.tests.idkeys.TestGeneratedKeys
org.apache.maven.surefire.booter.SurefireExecutionException: Could not initialize class com.avaje.ebean.Ebean; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.avaje.ebean.Ebean
java.lang.NoClassDefFoundError: Could not initialize class com.avaje.ebean.Ebean
        at com.avaje.tests.lib.EbeanTestCase.getServer(EbeanTestCase.java:32)
        at com.avaje.tests.lib.EbeanTestCase.run(EbeanTestCase.java:21)
        at junit.framework.TestSuite.runTest(TestSuite.java:255)
        at junit.framework.TestSuite.run(TestSuite.java:250)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:115)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:102)
        at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
        at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
```

**Comment by rbygrave** [comment]
Excellent work.  I have pushed up commit 961b219 which matches your fix.  

Thanks, Rob.
