### ISSUE TITLE
EBean 4.5.3 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm/avaje-ebeanorm#238]
I got some times java.lang.StackOverflowError exception in EBean code.
```
java.lang.StackOverflowError
	at com.avaje.ebean.bean.EntityBeanIntercept.getPropertyLength(EntityBeanIntercept.java:454)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:602)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
...
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
```
Stacktrace has 1024 lines and almost all of them are com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615).
For now I don't know which EBean command is called from my code. I will try to add more debug informations for this situation.

My application is conneced to Microsoft SQL Server database.

**Comment by Ryszard-Trojnacki** [comment]
With disabled stacktrace limit i have:
```
java.lang.StackOverflowError
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:422)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
... x9069
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.addDirtyPropertyValues(EntityBeanIntercept.java:615)
	at com.avaje.ebean.bean.EntityBeanIntercept.getDirtyValues(EntityBeanIntercept.java:594)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.getUpdatedValues(PersistRequestBean.java:212)
	at pl.euroimpex.dataaccess.core.engine.EbeanUtils.getOldValues(EbeanUtils.java:23)
	at pl.euroimpex.dataaccess.core.engine.EbeanServerSourceImpl.preUpdate(EbeanServerSourceImpl.java:820)
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:72)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:448)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:474)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:289)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:179)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:197)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1456)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1449)
```
And this exception occurs also with mySQL database. Therefore I think it is not database platform specific problem.

**Comment by rbygrave** [comment]
Hi,

Yes, I had a look at this last night.  I think there is something
interesting with part of the model - specifically an @Embedded bean seems
to have a recursive relationship or something like that.  Do you have any
@Embedded beans that have interesting relationships?

Thanks,Rob.

**Comment by Ryszard-Trojnacki** [comment]
Hi,

I don't use @Embedded in my program.

I think that in my code only one field is changed (Integer), but I'm not 100% sure. 
I will add logging to **addDirtyPropertyValues** method when stack trace is big.

Results will be prepared for tommorow (my time zone).

Greetings,
Rysiek

**Comment by Ryszard-Trojnacki** [comment]
As promised I added few log lines to **addDirtyPropertyValues** method:
```java
  public void addDirtyPropertyValues(Map<String,ValuePair> dirtyValues, String prefix) {
	  {
		  StackTraceElement[] st=Thread.currentThread().getStackTrace();
		  if(st.length>100) {
			  StringBuilder sb=new StringBuilder();
			  sb.append("addDirtyPropertyValues[").append(st.length).append("] prefix=").append(prefix);
			  sb.append("\n\tdirtyValues: ");
			  for(Entry<String, ValuePair> e : dirtyValues.entrySet()) {
				  sb.append(e.getKey()).append("=").append(e.getValue().getOldValue()).append("=>").append(e.getValue().getNewValue());
			  }
			  sb.append("\n");
			  sb.append("\tentity (").append(owner.getClass().getName()).append(") ").append(owner);
			  System.out.println(sb.toString());
		  }
	  }
// rest of addDirtyPropertyValues method unmodified
```
And my output is now:
```
INFO |12:21:32|STDOUT - addDirtyPropertyValues[101] prefix=printer.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.data.Printer) Printer#5
INFO |12:21:32|STDOUT - addDirtyPropertyValues[102] prefix=currentState.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.service.data.PrinterState) PrinterState#355
INFO |12:21:32|STDOUT - addDirtyPropertyValues[103] prefix=printer.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.data.Printer) Printer#5
INFO |12:21:32|STDOUT - addDirtyPropertyValues[104] prefix=currentState.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.service.data.PrinterState) PrinterState#355
INFO |12:21:32|STDOUT - addDirtyPropertyValues[105] prefix=printer.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.data.Printer) Printer#5
INFO |12:21:32|STDOUT - addDirtyPropertyValues[106] prefix=currentState.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.service.data.PrinterState) PrinterState#355
INFO |12:21:32|STDOUT - addDirtyPropertyValues[107] prefix=printer.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.data.Printer) Printer#5
INFO |12:21:32|STDOUT - addDirtyPropertyValues[108] prefix=currentState.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.service.data.PrinterState) PrinterState#355
INFO |12:21:32|STDOUT - addDirtyPropertyValues[109] prefix=printer.
	dirtyValues: 
	entity (pl.euroimpex.dataaccess.printapps.data.Printer) Printer#5
```
And the entity Printer (it is very big I have cut most of it):
```java
@Table(name="printers")
@Entity(name="printers")
public class Printer implements PrinterModel {
	@Column(name="id") @Id @GeneratedValue(strategy=GenerationType.TABLE) private Long id;
	@Column(name="dwid",nullable=false) private DataWarehouseId dataWarehouseId;
	@Column(name="flags", nullable=false) private long allFlags=0L;
	@JoinColumn(name="current_state_id") @ManyToOne private PrinterState currentState;
	@JoinColumn(name="last_swap_cyan_id")		@OneToOne private PrinterState lastTonerSwapCyan;
	@JoinColumn(name="last_swap_magenta_id")	@OneToOne private PrinterState lastTonerSwapMagenta;
	@JoinColumn(name="last_swap_yellow_id")		@OneToOne private PrinterState lastTonerSwapYellow;
	@JoinColumn(name="last_swap_black_id")		@OneToOne private PrinterState lastTonerSwapBlack;
...
}
```
PrinterState:
```java
@Entity
@Table(name="printers_state")
public class PrinterState implements PrinterStateModel {
	@Column(name="id") @Id @GeneratedValue(strategy=GenerationType.AUTO) private Long id;
	@Column(name="dwid",nullable=false) private DataWarehouseId dwId;
	@Column(name="flags",nullable=false) private long allFlags=0L;
	@JoinColumn(name="printer_id") @ManyToOne private Printer printer;
}
```
It seems that **addDirtyPropertyValues** is in a infinite loop because of connection between Printer <-> PrinterState.

**Comment by rbygrave** [comment]
I have not been able to reproduce the issue yet ... but it looks to me like:

BeanPropertyAssocOne line 522 should (additionally check for embedded boolean flag so):
if (embedded && value instanceof EntityBean) {
...
and similarly line 531

Some of the code comments in EntityBeanIntercept are now incorrect as embeddedOwner is only intended for use by embedded beans now.

**Comment by Ryszard-Trojnacki** [comment]
I have seen your commit with test code.

I'm trying to change your test case to reproduce my exception, which occurs occasionally (not always).

**Comment by rbygrave** [comment]
Ok. I've taken a guess ... and think commit a447361 might resolve the issue.  Really only need to undo the changes in BeanPropertyAssocOne line 522 and 531 if I need to back it out.

Perhaps you can see if that resolves it (in general it should as there is no @Embedded beans here).

**Comment by Ryszard-Trojnacki** [comment]
So far (after few hours of testing) I didn't get StackOverflowError. 
Before updating I got this error every dozen minutes.

So I think that commit a447361 resolved this problem for me, but I will check for this till the end of week to 100% sure.

Thanks!

**Comment by rbygrave** [comment]
Ok great.

**Comment by Ryszard-Trojnacki** [comment]
Application was tested for 3 days without any StackOverflowError then I'm sure that commit a447361 did the trick.

Thanks once again for solving this.

**Comment by jwaterloo** [comment]
What release is this a part of?

**Comment by rbygrave** [comment]
Looks like 4.5.5
