### ISSUE TITLE
Error getting _ebean_props field on type class com.avaje.ebean.meta.MetaAutoFetchStatistic

### ISSUE THREAD

**Issue by tonyzhang2020** [ebean-orm/avaje-ebeanorm#255]
I got a problem when testing the project,please help 

Issue detail:

java.lang.ExceptionInInitializerError
	at com.heiyoubang.data.DataRepository.<clinit>(DataRepository.java:29)
	at com.heiyoubang.data.AppTest.testDb(AppTest.java:35)
Caused by: java.lang.IllegalStateException: Error getting _ebean_props field on type class com.avaje.ebean.meta.MetaAutoFetchStatistic
	at com.avaje.ebeaninternal.server.properties.BeanPropertiesReader.getProperties(BeanPropertiesReader.java:42)
	at com.avaje.ebeaninternal.server.properties.BeanPropertiesReader.<init>(BeanPropertiesReader.java:18)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setBeanReflect(BeanDescriptorManager.java:1271)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1107)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1023)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:502)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:219)
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:119)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:142)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:73)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:38)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:52)
	at com.avaje.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:205)
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:167)
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:133)
	at com.avaje.ebean.Ebean.<clinit>(Ebean.java:127)
	... 30 more
Caused by: java.lang.NoSuchFieldException: _ebean_props
	at java.lang.Class.getField(Class.java:1584)
	at com.avaje.ebeaninternal.server.properties.BeanPropertiesReader.getProperties(BeanPropertiesReader.java:38)
	... 45 more

**Comment by rbygrave** [comment]
I think this can be closed.  The issue was a mismatch of versions between the agent/maven plugin and ebean.

**Comment by tonyzhang2020** [comment]
Yes,I fixed it already,thanks.

**Comment by darnir** [comment]
Can you please explain what the issue was? Because I currently have a similar problem

**Comment by rbygrave** [comment]
> The issue was a mismatch of versions between the agent/maven plugin and ebean.

What this means is that 
1. the agent and maven versions should be the same 
2. Ebean 4.x and greater requires agent 4.x.   Agent versions 3.x are only valid for Ebean 3.x.
