### ISSUE TITLE
Problem with RawSql: query does not contain any named bind parameters?

### ISSUE THREAD

**Issue by ForNeVeR** [ebean-orm/avaje-ebeanorm#259]
Is there some problem with RawSql caching? I'm using the recommended `4.5.4` version of ebean (I had the same problem with older `2.8.1` though), and the following code is throwing an exception:

```java
	public static void main(String[] args) {
		System.out.println(call());
		System.out.println(call()); // <- exception from this invocation
	}

	private static int call() {
		String sql = "select * from my_table where id = :id and name = :name";
		RawSql rawSql = RawSqlBuilder.unparsed(sql)
				.columnMapping("id", "id")
				.columnMapping("name", "name")
				.create();
		Query<MyTable> query = Ebean.find(MyTable.class);
		query.setParameter("id", "1");
		query.setParameter("name", "name");
		query.setRawSql(rawSql);
		return query.findList().size();
	}
```

It throws the following exception:

```
Exception in thread "main" javax.persistence.PersistenceException: query does not contain any named bind parameters?
    at com.avaje.ebeaninternal.server.util.BindParamsParser.parseNamedParams(BindParamsParser.java:119)
    at com.avaje.ebeaninternal.server.util.BindParamsParser.parseNamedParams(BindParamsParser.java:113)
    at com.avaje.ebeaninternal.server.util.BindParamsParser.parseSql(BindParamsParser.java:99)
    at com.avaje.ebeaninternal.server.util.BindParamsParser.parse(BindParamsParser.java:47)
    at com.avaje.ebeaninternal.server.util.BindParamsParser.parse(BindParamsParser.java:43)
    at com.avaje.ebeaninternal.server.query.CQueryPredicates.buildBindWhereRawSql(CQueryPredicates.java:239)
    at com.avaje.ebeaninternal.server.query.CQueryPredicates.prepare(CQueryPredicates.java:276)
    at com.avaje.ebeaninternal.server.query.CQueryPredicates.prepare(CQueryPredicates.java:264)
    at com.avaje.ebeaninternal.server.query.CQueryBuilder.buildQuery(CQueryBuilder.java:193)
    at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162)
    at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:80)
    at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:284)
    at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1367)
    at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:933)
    at me.fornever.ebeanbug.Application.call(Application.java:25)
    at me.fornever.ebeanbug.Application.main(Application.java:12)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

_(Please note - the function works on the first call but fails on the second.)_

I've created a sample project reproducing this bug: https://github.com/ForNeVeR/ebean-issue-259

What am I doing wrong? If there is a bug in ebean then is there some workaround?

Note that I'm using MySQL.

**Comment by ForNeVeR** [comment]
I want to investigate that further, fix that and send a pull request. Maybe you guys have some considerations about how it can be fixed and what's an issue here?

**Comment by rbygrave** [comment]
Sorry, I have not looked at this yet myself.  I should be able to do so
shortly.

**Comment by ForNeVeR** [comment]
Aha, it seems to require `preWhere` at [CQueryPredicated:237](https://github.com/ebean-orm/avaje-ebeanorm/blob/avaje-ebeanorm-4.5.4/src/main/java/com/avaje/ebeaninternal/server/query/CQueryPredicates.java#L237), but the `preWhere` field exists only for the parsed queries, not the unparsed ones.

It seems to work fine with `getSql().getPreWhere()` replaced by `getSql().getUnparsedSql()` and we should obviously try to take that only if `!sql.isParsed()`. But will it be safe for all other ebean facilities? Maybe the code should not ever visit this point for the unparsed queries?

**Comment by ForNeVeR** [comment]
BTW, I'd suggest you to setup some open test system like [Travis](https://travis-ci.org/) so it would be easier to test their changes for such a random contributors as I am.
