### ISSUE TITLE
Trying to insert() or save() an entity with no @Id results in NPE

### ISSUE THREAD

**Issue by paol** [ebean-orm/avaje-ebeanorm#260]
Ebean version: 4.5.4

I have an entity with no identity fields. Any attempt to insert a new instance of this entity results in a NullPointerException.

Upon looking at the ebean code, the problem lies in com.avaje.ebeaninternal.server.persist.dml.InsertHandler. The error happens because the method bind() sets the flag useGeneratedKeys even if the entity has no key. Then, because the flag is set, the method getPstmt() ends up calling prepareStatement with a null second parameter, which is not a valid call.

I think this is related to bug #130, but that was closed with no resolution and the workaround suggested there (using Transaction.setBatchGetGeneratedKeys) doesn't seem to work.

**Comment by rbygrave** [comment]
Can you post up the stack trace?  That way if a test case is created it can
confirmed to be the same issue.

Thanks, Rob.

**Comment by paol** [comment]
Sure, here it is.

```
java.lang.NullPointerException: null
	at org.postgresql.core.Utils.appendEscapedIdentifier(Utils.java:141)
	at org.postgresql.jdbc3.AbstractJdbc3Statement.addReturning(AbstractJdbc3Statement.java:168)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.prepareStatement(AbstractJdbc3Connection.java:468)
	at com.avaje.ebeaninternal.server.lib.sql.PooledConnection.prepareStatement(PooledConnection.java:908)
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.getPstmt(InsertHandler.java:116)
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:99)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:76)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57)
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:59)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:446)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:480)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:261)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:211)
	at com.avaje.ebeaninternal.server.core.DefaultServer.insert(DefaultServer.java:1532)
	at com.avaje.ebeaninternal.server.core.DefaultServer.insert(DefaultServer.java:1525)
	at com.avaje.ebean.Model.insert(Model.java:227)
	at bimk.domain.productmanager.base.ProductManager.recordView(ProductManager.java:772)
	at bimk.domain.productmanager.base.TestProductManagerService.testRecordView(TestProductManagerService.java:1251)
```
