### ISSUE TITLE
PostgreSQL java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4Connection.isValid(int)

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm/avaje-ebeanorm#266]
When using (running maven tests) Ebean with PostgreSQL there is an error with connection because there is no heartbeatsql and method isValid is used:
```java
public class DataSourcePool implements DataSource {
    private boolean testConnection(Connection conn) throws SQLException {

        if (heartbeatsql == null) {
            return conn.isValid(heartbeatTimeoutSeconds);
        }
}
```
I think that for PostgreSQL connection there should be a default heartbeat sql command:
```sql
SELECT NOW()
```

Whole exception:
```
ava.sql.SQLFeatureNotSupportedException: Metoda org.postgresql.jdbc4.Jdbc4Connection.isValid(int)nie jest jeszcze obsługiwana.
	at org.postgresql.Driver.notImplemented(Driver.java:753) ~[postgresql-9.1-901-1.jdbc4.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.isValid(AbstractJdbc4Connection.java:120) ~[postgresql-9.1-901-1.jdbc4.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.isValid(Jdbc4Connection.java:21) ~[postgresql-9.1-901-1.jdbc4.jar:na]
	at com.avaje.ebeaninternal.jdbc.ConnectionDelegator.isValid(ConnectionDelegator.java:220) ~[classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.testConnection(DataSourcePool.java:538) [classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.checkDataSource(DataSourcePool.java:413) [classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.returnTheConnection(DataSourcePool.java:625) [classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.returnConnectionForceClose(DataSourcePool.java:609) [classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.PooledConnection.close(PooledConnection.java:512) [classes/:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.deactivate(JdbcTransaction.java:735) [classes/:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:896) [classes/:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:874) [classes/:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.end(JdbcTransaction.java:907) [classes/:na]
	at com.avaje.ebeaninternal.server.ddl.DdlGenerator.runScript(DdlGenerator.java:239) [classes/:na]
	at com.avaje.ebeaninternal.server.ddl.DdlGenerator.runDdl(DdlGenerator.java:92) [classes/:na]
	at com.avaje.ebeaninternal.server.ddl.DdlGenerator.execute(DdlGenerator.java:64) [classes/:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.executePlugins(DefaultServer.java:237) [classes/:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:163) [classes/:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:73) [classes/:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:38) [classes/:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:52) [classes/:na]
	at com.avaje.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:210) [classes/:na]
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:168) [classes/:na]
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:133) [classes/:na]
	at com.avaje.ebean.Ebean.<clinit>(Ebean.java:127) [classes/:na]
	at com.avaje.tests.model.basic.ResetBasicData.<clinit>(ResetBasicData.java:16) [test-classes/:na]
	at com.avaje.tests.basic.TestUpdateManyToOne.test(TestUpdateManyToOne.java:18) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59) [surefire-junit4-2.5.jar:2.5]
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:115) [surefire-api-2.5.jar:2.5]
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:102) [surefire-api-2.5.jar:2.5]
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180) [surefire-api-2.5.jar:2.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350) [surefire-booter-2.5.jar:2.5]
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021) [surefire-booter-2.5.jar:2.5]
```
(Tried with 9.1-901-1.jdbc4 and 8.4-701.jdbc4)

The same is with **heartbeatTimeoutSeconds**:
```
org.postgresql.util.PSQLException: Metoda org.postgresql.jdbc4.Jdbc4Statement.setQueryTimeout(int)nie jest jeszcze obsługiwana.
	at org.postgresql.Driver.notImplemented(Driver.java:753) ~[postgresql-8.4-701.jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setQueryTimeout(AbstractJdbc2Statement.java:635) ~[postgresql-8.4-701.jdbc4.jar:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.testConnection(DataSourcePool.java:546) [classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.checkDataSource(DataSourcePool.java:413) [classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.returnTheConnection(DataSourcePool.java:625) [classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.returnConnectionForceClose(DataSourcePool.java:609) [classes/:na]
	at com.avaje.ebeaninternal.server.lib.sql.PooledConnection.close(PooledConnection.java:512) [classes/:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.deactivate(JdbcTransaction.java:735) [classes/:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:896) [classes/:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.rollback(JdbcTransaction.java:874) [classes/:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.end(JdbcTransaction.java:907) [classes/:na]
	at com.avaje.ebeaninternal.server.ddl.DdlGenerator.runScript(DdlGenerator.java:239) [classes/:na]
	at com.avaje.ebeaninternal.server.ddl.DdlGenerator.runDdl(DdlGenerator.java:92) [classes/:na]
	at com.avaje.ebeaninternal.server.ddl.DdlGenerator.execute(DdlGenerator.java:64) [classes/:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.executePlugins(DefaultServer.java:237) [classes/:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:163) [classes/:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:73) [classes/:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:38) [classes/:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:52) [classes/:na]
	at com.avaje.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:210) [classes/:na]
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:168) [classes/:na]
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:133) [classes/:na]
```

**Comment by rbygrave** [comment]
In the examples/x-postgre-features project I'm using:

    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>9.3-1102-jdbc41</version>
    </dependency>

... and the connection.isValid() method is supported and works.

**Comment by rbygrave** [comment]
Setting a default heartbeat sql command ... would mean that the connection.isValid() method would not be used.

Looking at DataSourcePool.testConnection() ... to me it is preferable to use 
connection.isValid(heartbeatTimeoutSeconds);  when compared to executing a statement potentially with preparedStatement.setQueryTimeout(heartbeatTimeoutSeconds);

So at this stage I'd prefer to not have the default heartbeat sql leaving users to either set it or use a later jdbc driver like 9.3-1102-jdbc41 that supports isValid().

Thoughts?

**Comment by rbygrave** [comment]
So again, I much prefer to use connection.isValid() if possible ... and it is possible with later Postgres JDBC drivers ... so I think we should close this as:  'please update your jdbc driver or if not possible please specify a heartbeat query'.

Closing.

Cheers, Rob.
