### ISSUE TITLE
OneToMany has error

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#267]
```
@MappedSuperclass
public abstract class BaseModel extends Model {
    @Id
    @GeneratedValue
    public Long id;
    @CreatedTimestamp
    public Timestamp createTime;
    @UpdatedTimestamp
    public Timestamp updateTime;

}

```

```
@Table(name = "rt_documents")
public class Documents extends BaseModel {
    @Column(length = 50)
    public String docName;
    @OneToMany(cascade = {CascadeType.ALL})
    @JoinColumns({
            @JoinColumn(name = "object_id", referencedColumnName = "id"),
            @JoinColumn(name = "object_entity", referencedColumnName = "doc_name")
    })
    public List<Documentauth> documentauth;

}
```

```
@Table(name = "rt_documentauth")
public class Documentauth extends Model {

    @Embeddable
    public static class Id implements Serializable {

        public Integer objectId;

        @Column(length = 100)
        public String objectEntity;

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Id id = (Id) o;

            if (objectEntity != null ? !objectEntity.equals(id.objectEntity) : id.objectEntity != null) return false;
            if (objectId != null ? !objectId.equals(id.objectId) : id.objectId != null) return false;

            return true;
        }

        @Override
        public int hashCode() {
            int result = objectId != null ? objectId.hashCode() : 0;
            result = 31 * result + (objectEntity != null ? objectEntity.hashCode() : 0);
            return result;
        }
    }

    @javax.persistence.Id
    public Id id;

    @Column(length = 50)
    public String orgId;

    @CreatedTimestamp
    public Date createTime;
}
```

```
22:38:24.350 [main] ERROR c.a.e.s.deploy.BeanPropertyAssoc - No Imported Id column for [id] in table [rt_documents]
22:38:24.375 [main] ERROR c.a.e.s.deploy.BeanDescriptorManager - Error in deployment
javax.persistence.PersistenceException: Error with the Join on [com.sinitek.fiaame.models.routine.Documents.documentauth]. Could not find the matching foreign key for [id] in table[rt_documentauth]? Perhaps using a @JoinColumn with the name/referencedColumnName attributes swapped?
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.findMatch(BeanPropertyAssocMany.java:745) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.createExported(BeanPropertyAssocMany.java:707) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.initialise(BeanPropertyAssocMany.java:139) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.initialiseOther(BeanDescriptor.java:541) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.initialiseAll(BeanDescriptorManager.java:345) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:235) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:119) [avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:142) [avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:38) [avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:79) [avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:64) [avaje-ebeanorm-4.5.5.jar:na]
	at ameba.db.ebean.EbeanFeature.configure(EbeanFeature.java:195) [ameba-0.1.6e.jar:0.1.6e]
	at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:714) [jersey-common-2.17.jar:na]
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:644) [jersey-common-2.17.jar:na]
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:816) [jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:426) [jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:166) [jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler$3.run(ApplicationHandler.java:327) [jersey-server-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:289) [jersey-common-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:286) [jersey-common-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:286) [jersey-common-2.17.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:324) [jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:289) [jersey-server-2.17.jar:na]
	at ameba.container.grizzly.server.http.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:284) [ameba-container-grizzly-0.1.6e.jar:na]
	at ameba.container.grizzly.server.http.GrizzlyHttpContainerProvider.createContainer(GrizzlyHttpContainerProvider.java:18) [ameba-container-grizzly-0.1.6e.jar:na]
	at org.glassfish.jersey.server.ContainerFactory.createContainer(ContainerFactory.java:81) [jersey-server-2.17.jar:na]
	at ameba.container.grizzly.server.GrizzlyContainer.configureHttpContainer(GrizzlyContainer.java:172) [ameba-container-grizzly-0.1.6e.jar:na]
	at ameba.container.Container.<init>(Container.java:35) [ameba-0.1.6e.jar:0.1.6e]
	at ameba.container.grizzly.server.GrizzlyContainer.<init>(GrizzlyContainer.java:69) [ameba-container-grizzly-0.1.6e.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) [na:1.8.0_25]
	at ameba.container.Container.create(Container.java:46) [ameba-0.1.6e.jar:0.1.6e]
	at ameba.Ameba.bootstrap(Ameba.java:79) [ameba-0.1.6e.jar:0.1.6e]
	at ameba.Ameba.bootstrap(Ameba.java:70) [ameba-0.1.6e.jar:0.1.6e]
	at ameba.Ameba.main(Ameba.java:56) [ameba-0.1.6e.jar:0.1.6e]
	at com.sinitek.fiaame.Main.main(Main.java:10) [test-classes/:na]
```

**Comment by ashok4ch** [comment]
Have you got any solution for this issue, I am also getting the same issue.
