### ISSUE TITLE
ArrayIndexOutOfBoundsException during compilation

### ISSUE THREAD

**Issue by eximius313** [ebean-orm/avaje-ebeanorm#271]
Hi,

When I try to compile this class (using Play Framework 2.3.8):
@Entity
@Table(name="something")
public class Something extends Model {
	@Id
	@Constraints.Min(10)
	private Long id;
	
	@OneToMany
	private List<SomeEntity> someEntities;
	
	public void setId(Long id) {
		this.id = id;
	}
	
	public List<SomeEntity> getSomeEntities() {
		return someEntities;
	}
	
	public void setSomeEntities(List<SomeEntity> someEntities) {
		this.someEntities = someEntities;
	}

	@Transient
	public Map<SomeState, Long> getSomeStats(){
		return getSomeEntities().parallelStream().collect(Collectors.groupingBy(a -> a.getState(), Collectors.counting()));
	}
}

@Entity
@Table(name = "some")
public class SomeEntity extends Model {
	public static enum SomeState{
		NEW,
		PENDING
	}
	
	@Id
	@Constraints.Min(10)
	private Long id;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Constraints.Required
	private SomeState state;

	public SomeState getState() {
		return state;
	}

	public void setState(SomeState state) {
		this.state = state;
	}
}
EBean throws following Exception:

<code>
java.lang.ArrayIndexOutOfBoundsException: 11584
        at com.avaje.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:174)
        at com.avaje.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:153)
        at com.avaje.ebean.enhance.agent.Transformer.detect(Transformer.java:251)
        at com.avaje.ebean.enhance.agent.Transformer.transform(Transformer.java:106)
        at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:55)
        at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:39)
        at com.avaje.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:141)
        at com.avaje.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
        at com.avaje.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:90)
        at play.PlayCommands$$anonfun$PostCompile$1.apply(PlayCommands.scala:142)
        at play.PlayCommands$$anonfun$PostCompile$1.apply(PlayCommands.scala:75)
        at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
        at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
</code>

Exception disappears when I comment this lines:
	@Transient
	public Map<SomeState, Long> getApplyStats(){
		return getSomeEntities().parallelStream().collect(Collectors.groupingBy(a -> a.getState(), Collectors.counting()));
	}

Can you fix it?
Kind Regards

**Comment by eximius313** [comment]
And I don't know why Github formats this class in such a weird way...

**Comment by rbygrave** [comment]
You must use Ebean 4.x agent to use java8 features.

refer to https://github.com/ebean-orm/avaje-ebeanorm-agent/issues/10

You will likely be using an old Ebean at this stage hence the error.
The only solution is to migrate to 4.x of Ebean.


Cheers, Rob.

**Comment by eximius313** [comment]
You are right!
I'm using Play Framework 2.3.8 and as I see, support for Ebean 4.x is from version 2.4, which is currently release candidate.

Thanks

**Comment by rbygrave** [comment]
I'll close this one then.
Cheers, Rob.
