### ISSUE TITLE
please check fetchPaths not null - NPE on OrmQueryDetail.convertManyFetchJoinsToQueryJoins(OrmQueryDetail.java:331)

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#277]
```
java.lang.NullPointerException: null
	at com.avaje.ebeaninternal.server.querydefn.OrmQueryDetail.convertManyFetchJoinsToQueryJoins(OrmQueryDetail.java:331) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.convertManyFetchJoinsToQueryJoins(DefaultOrmQuery.java:374) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryRequest(DefaultServer.java:1053) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryRequest(DefaultServer.java:1012) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1358) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:933) ~[avaje-ebeanorm-4.5.5.jar:na]
```

please check fetchPaths not null or throw a path properties error exception

**Comment by icode** [comment]
@rbygrave please check path like root path

**Comment by rbygrave** [comment]
I'm trying to determine what you mean by this.  An example always helps.

**Comment by icode** [comment]
```
for (String fetchPath : fetchPaths.keySet()) {
      ElPropertyDeploy elProp = beanDescriptor.getElPropertyDeploy(fetchPath);
// =====> add check elProp not null
      if (elProp != null && elProp.containsManySince(manyFetchProperty)) {

        // this is a join to a *ToMany
        OrmQueryProperties chunk = fetchPaths.get(fetchPath);
        if (chunk.isFetchJoin() && !isLazyLoadManyRoot(lazyLoadManyPath, chunk)
            && !hasParentSecJoin(lazyLoadManyPath, chunk)) {
          // this is a 'fetch join' (included in main query)
          if (fetchJoinFirstMany) {
            // letting the first one remain a 'fetch join'
            fetchJoinFirstMany = false;
            manyFetchProperty = fetchPath;
          } else {
            // convert this one over to a 'query join'
            manyChunks.add(chunk);
          }
        }
      }
    }
```

```
query.fetch("notHaveProps", "notHaveProps", config);
query.findList()//throw exception nullPoint
```

**Comment by rbygrave** [comment]
Thanks. I understand.
