### ISSUE TITLE
not init attribute after set value throw null point

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#281]
```
public class InnerReport extends BaseModel
{
    private static final String SOURCE_ENTITY = "REPORT";
    
    @OneToOne(cascade = {CascadeType.REMOVE},
              fetch = FetchType.LAZY)
    @JoinColumn(name = "id", referencedColumnName = "source_id", insertable = false)
    public Forecast forecast;

    @DiscriminatorValue(SOURCE_ENTITY)
    public static class Forecast extends Stockforecast
    {
        @JoinColumn(name = "source_id", referencedColumnName = "id",
                    unique = false, insertable = false)
        public InnerReport innerReport;
    }

}
```

```
InnerReport report = Ebean.json().toObject(InnerReport.class, "{}");
report.save();
// other service ...
 InnerReport.Forecast f = new InnerReport.Forecast()
report.setForecast(f); // throw excptions
f.innerReport=report;
f.save();
```

```
javax.persistence.PersistenceException: Error loading on models.routine.InnerReport.forecast
	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:88) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne.load(BeanPropertyAssocOne.java:544) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:236) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.readRow(CQuery.java:497) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.readBeanInternal(CQuery.java:524) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.readBean(CQuery.java:509) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:226) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:115) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:226) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1143) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1157) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:951) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:433) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:358) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:473) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:715) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:680) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:775) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.sinitek.fiaame.models.routine.InnerReport._ebean_get_forecast(InnerReport.java:6) ~[java:na]
	at com.sinitek.fiaame.models.routine.InnerReport._ebean_set_forecast(InnerReport.java:1) ~[java:na]
	at com.sinitek.fiaame.models.routine.InnerReport.setForecast(InnerReport.java) ~[java:na]
	at com.sinitek.fiaame.resources.routine.InnerReportResource.postInsertModel(InnerReportResource.java:162) ~[java:na]
	at com.sinitek.fiaame.resources.routine.InnerReportResource.postInsertModel(InnerReportResource.java:26) ~[java:na]
	at ameba.db.ebean.internal.ModelResourceStructure$1.run(ModelResourceStructure.java:148) ~[ameba-0.1.6e.jar:0.1.6e]
	at ameba.db.ebean.internal.ModelResourceStructure$15.call(ModelResourceStructure.java:717) ~[ameba-0.1.6e.jar:0.1.6e]
	at ameba.db.ebean.internal.ModelResourceStructure.processCheckRowCountError(ModelResourceStructure.java:684) ~[ameba-0.1.6e.jar:0.1.6e]
	at ameba.db.ebean.internal.ModelResourceStructure.executeTx(ModelResourceStructure.java:713) ~[ameba-0.1.6e.jar:0.1.6e]
	at ameba.db.ebean.internal.ModelResourceStructure.executeTx(ModelResourceStructure.java:743) ~[ameba-0.1.6e.jar:0.1.6e]
	at ameba.db.ebean.internal.ModelResourceStructure.insert(ModelResourceStructure.java:143) ~[ameba-0.1.6e.jar:0.1.6e]
	at ameba.db.ebean.internal.AbstractModelResource.insert(AbstractModelResource.java:51) ~[ameba-0.1.6e.jar:0.1.6e]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_25]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_25]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.17.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.17.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[jersey-common-2.17.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288) ~[jersey-server-2.17.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110) ~[jersey-server-2.17.jar:na]
	at ameba.container.grizzly.server.http.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:150) ~[ameba-container-grizzly-0.1.6e.jar:na]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) ~[grizzly-http-server-2.3.20.jar:2.3.20]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) ~[grizzly-framework-2.3.20.jar:2.3.20]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) ~[grizzly-framework-2.3.20.jar:2.3.20]
	at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
Caused by: java.lang.NullPointerException: null
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne$Reference.read(BeanPropertyAssocOne.java:694) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne.read(BeanPropertyAssocOne.java:516) ~[avaje-ebeanorm-4.5.5.jar:na]
	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:77) ~[avaje-ebeanorm-4.5.5.jar:na]
	... 55 common frames omitted
```

**Comment by rbygrave** [comment]
See the commit above - I am not able to reproduce the problem.  

Please create a failing test case.

Thanks.

**Comment by icode** [comment]
this is DiscriminatorValue OneToOne mapping error. I use id and type mapping data, what's the mapping type ? OneToOne or ManyToOne?

**Comment by rbygrave** [comment]
I don't understand your comment.  What I'd like you to do is modify the model/test that I added in the commit above so that it fails ... or create your own standalone failing test case.
