### ISSUE TITLE
ENH: Add to transaction setUpdateAllLoadedProperties()  -  force update all properties api

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#296]
Can add a API for update ? Not global API, for one request exec

**Comment by rbygrave** [comment]
Add to transaction:

```java
  /**
   * Set to true when you want all loaded properties to be included in the update
   * (rather than just the changed properties).
   * <p>
   *   You might set this when using JDBC batch in order to get multiple updates
   *   with slightly different sets of changed properties into the same statement
   *   and hence better JDBC batch performance.
   * </p>
   */
  void setUpdateAllLoadedProperties(boolean updateAllLoadedProperties);
```

**Comment by icode** [comment]
@rbygrave Tanks for support, this very useful for RESTful `PUT` method!

**Comment by rbygrave** [comment]
ok, I think this is best on the transaction.  I can't see people needing this without jdbc batch processing.

**Comment by rbygrave** [comment]
Done then.

**Comment by icode** [comment]
@rbygrave  sorry!

But i want only update all properties for one model on the batch transaction.


```
    public Response replace(@PathParam("id") final ID id, @NotNull @Valid final M model) throws Exception {
        matchedReplace(id, model);
        final ID mId = tryConvertId(id);
        BeanDescriptor descriptor = getModelBeanDescriptor();
        descriptor.convertSetId(mId, (EntityBean) model);
// my now use for update all
        EbeanUtils.forceUpdateAllProperties(server, model);

        final Response.ResponseBuilder builder = Response.noContent();
        executeTx(new TxRunnable() {
            @Override
            public void run(Transaction t) throws Exception {
                preReplaceModel(model);// this can update/create/delete other model for service
                replaceModel(model);// this need replace this model all properties
                postReplaceModel(model);// this can update/create/delete other model for service
// trans commit;
            }
        }, new TxRunnable() {
            @Override
            public void run(Transaction t) throws Exception {
                logger().debug("not found model record, insert a model record.");
                preInsertModel(model);
                insertModel(model);
                postInsertModel(model);
                builder.status(Response.Status.CREATED).location(buildLocationUri(mId, true));
            }
        });
        return builder.build();
    }
```

**Comment by rbygrave** [comment]
> But i want only update all properties for one model on the batch
transaction.

Why?

**Comment by icode** [comment]
Because optimize, `preReplaceModel` is child class callback use for business, this callback can have update other model, but this model not need update all properties. Then `replaceModel` method replace all model properties. So, this batch transaction only update one `model`'s all properties, other model update change properties.

**Comment by icode** [comment]
e.g:

```
// model = from restful json
              final Transaction transaction = server.beginTransaction();
               try {
                    otherModel.setEmployeeId(123);
                    server.update(otherModel);// only update EmployeeId
                    server.update(model);// update all properties
                    t.commit();
                } catch (Throwable e) {
                    transaction.rollback(e);
                    throw e;
                } finally {
                    transaction.end();
                }
```

**Comment by icode** [comment]
@rbygrave Do you understand what I said?

`transaction.setUpdateAllLoadedProperties(false);`  this default true？？？

And i get a error on update, that update `id`, so database tell me `id can not be null`

**Comment by rbygrave** [comment]
No I don't understand.

> Because optimize ...

I don't understand what you are saying here. Maybe you are saying you want
it for a performance reason but that doesn't make sense to me given your
use case (the performance would come from better statement reuse) so no I
do not understand.

**Comment by icode** [comment]
@rbygrave I want update only one entity all properties in transaction, not all entity in transaction. I use at RESTful `PUT` request.

**Comment by rbygrave** [comment]
I understand that.  I don't understand why. What is the impact ...
something not working, some performance reason ... I don't understand why
you want to do that yet.

**Comment by icode** [comment]
@rbygrave I get this error

```
javax.persistence.PersistenceException: Error when batch flush on sql: update ir_report set create_empid=?, update_empid=?, title=?, author_names=?, attchment_flag=?, summary=?, industry_code=?, scode=?, approve_time=?, submit_time=?, archive_time=?, status=?, update_time=?, report_type=?, id=? where id=?
	at com.avaje.ebeaninternal.server.persist.BatchedPstmtHolder.flush(BatchedPstmtHolder.java:128) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.persist.BatchControl.flushPstmtHolder(BatchControl.java:198) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.persist.BatchControl.executeNow(BatchControl.java:212) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.persist.BatchedBeanHolder.executeNow(BatchedBeanHolder.java:93) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.persist.BatchControl.flush(BatchControl.java:252) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.persist.BatchControl.flush(BatchControl.java:219) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.flushBatch(JdbcTransaction.java:634) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.flushJdbcBatchOnQuery(DefaultOrmQueryEngine.java:46) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findIds(DefaultOrmQueryEngine.java:58) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findIds(OrmQueryRequest.java:234) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findIdsWithCopy(DefaultServer.java:1270) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findIds(DefaultServer.java:1262) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findIds(DefaultOrmQuery.java:938) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.util.DefaultExpressionList.findIds(DefaultExpressionList.java:183) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.sinitek.fiaame.resources.stockresearch.IndustryadviceResource.postInsertModel(IndustryadviceResource.java:138) ~[classes/:na]
	at com.sinitek.fiaame.resources.stockresearch.IndustryadviceResource.postInsertModel(IndustryadviceResource.java:35) ~[classes/:na]
	at ameba.db.ebean.support.ModelResourceStructure$1.run(ModelResourceStructure.java:161) ~[ameba-0.1.7-20150805.111044-234.jar:0.1.7-SNAPSHOT]
	at ameba.db.ebean.support.ModelResourceStructure$15.call(ModelResourceStructure.java:749) ~[ameba-0.1.7-20150805.111044-234.jar:0.1.7-SNAPSHOT]
	at ameba.db.ebean.support.ModelResourceStructure.processTransactionError(ModelResourceStructure.java:717) ~[ameba-0.1.7-20150805.111044-234.jar:0.1.7-SNAPSHOT]
	at ameba.db.ebean.support.ModelResourceStructure.executeTx(ModelResourceStructure.java:745) ~[ameba-0.1.7-20150805.111044-234.jar:0.1.7-SNAPSHOT]
	at ameba.db.ebean.support.ModelResourceStructure.executeTx(ModelResourceStructure.java:775) ~[ameba-0.1.7-20150805.111044-234.jar:0.1.7-SNAPSHOT]
	at ameba.db.ebean.support.ModelResourceStructure.insert(ModelResourceStructure.java:156) ~[ameba-0.1.7-20150805.111044-234.jar:0.1.7-SNAPSHOT]
	at ameba.db.ebean.support.AbstractModelResource.insert(AbstractModelResource.java:51) ~[ameba-0.1.7-20150805.111044-234.jar:0.1.7-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308) ~[jersey-server-2.19.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.19.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.19.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.19.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.19.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.19.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.19.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [jersey-server-2.19.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [jersey-server-2.19.jar:na]
	at ameba.container.grizzly.server.http.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:150) [ameba-container-grizzly-0.1.7.Alpha1.jar:na]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.21.jar:2.3.21]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.21.jar:2.3.21]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.21.jar:2.3.21]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
Caused by: java.sql.BatchUpdateException: Column 'id' cannot be null
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1819) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1281) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:559) ~[druid-1.0.15.jar:1.0.15]
	at com.avaje.ebeaninternal.server.persist.BatchedPstmt.executeAndCheckRowCounts(BatchedPstmt.java:127) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.persist.BatchedPstmt.executeBatch(BatchedPstmt.java:88) ~[avaje-ebeanorm-6.2.1.jar:na]
	at com.avaje.ebeaninternal.server.persist.BatchedPstmtHolder.flush(BatchedPstmtHolder.java:95) ~[avaje-ebeanorm-6.2.1.jar:na]
	... 48 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_75]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_75]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.Util.getInstance(Util.java:372) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1777) ~[mysql-connector-java-5.1.35.jar:5.1.35]
	... 53 common frames omitted
18:20:45.319 [Grizzly-worker(8)] INFO  ameba.filter.ResponseLoggingFilter - 184 * Server responded with a response on thread Grizzly-worker(8)
184 < 500
184 < Content-Type: application/json
{
  "success" : false,
  "code" : -949829417,
  "message" : "系统错误",
  "description" : "服务器遇到了一个未曾预料的状况，导致了它无法完成对请求的处理。",
  "errors" : [ {
    "code" : -949829417,
    "message" : "Error when batch flush on sql: update ir_report set create_empid=?, update_empid=?, title=?, author_names=?, attchment_flag=?, summary=?, industry_code=?, scode=?, approve_time=?, submit_time=?, archive_time=?, status=?, update_time=?, report_type=?, id=? where id=?",
    "source" : "public final javax.ws.rs.core.Response com.sinitek.fiaame.resources.stockresearch.IndustryadviceResource.insert(ameba.db.model.Model) throws java.lang.Exception"
  }, {
    "code" : -949829417,
    "message" : "Error when batch flush on sql: update ir_report set create_empid=?, update_empid=?, title=?, author_names=?, attchment_flag=?, summary=?, industry_code=?, scode=?, approve_time=?, submit_time=?, archive_time=?, status=?, update_time=?, report_type=?, id=? where id=?",
    "description" : "com.avaje.ebeaninternal.server.persist.BatchedPstmtHolder.flush(BatchedPstmtHolder.java:128)\ncom.avaje.ebeaninternal.server.persist.BatchControl.flushPstmtHolder(BatchControl.java:198)\ncom.avaje.ebeaninternal.server.persist.BatchControl.executeNow(BatchControl.java:212)\ncom.avaje.ebeaninternal.server.persist.BatchedBeanHolder.executeNow(BatchedBeanHolder.java:93)\ncom.avaje.ebeaninternal.server.persist.BatchControl.flush(BatchControl.java:252)\ncom.avaje.ebeaninternal.server.persist.BatchControl.flush(BatchControl.java:219)\ncom.avaje.ebeaninternal.server.transaction.JdbcTransaction.flushBatch(JdbcTransaction.java:634)\ncom.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.flushJdbcBatchOnQuery(DefaultOrmQueryEngine.java:46)\ncom.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findIds(DefaultOrmQueryEngine.java:58)\ncom.avaje.ebeaninternal.server.core.OrmQueryRequest.findIds(OrmQueryRequest.java:234)\ncom.avaje.ebeaninternal.server.core.DefaultServer.findIdsWithCopy(DefaultServer.java:1270)\ncom.avaje.ebeaninternal.server.core.DefaultServer.findIds(DefaultServer.java:1262)\ncom.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findIds(DefaultOrmQuery.java:938)\ncom.avaje.ebeaninternal.util.DefaultExpressionList.findIds(DefaultExpressionList.java:183)\ncom.sinitek.fiaame.resources.stockresearch.IndustryadviceResource.postInsertModel(IndustryadviceResource.java:138)\ncom.sinitek.fiaame.resources.stockresearch.IndustryadviceResource.postInsertModel(IndustryadviceResource.java:35)\nameba.db.ebean.support.ModelResourceStructure$1.run(ModelResourceStructure.java:161)\nameba.db.ebean.support.ModelResourceStructure$15.call(ModelResourceStructure.java:749)\nameba.db.ebean.support.ModelResourceStructure.processTransactionError(ModelResourceStructure.java:717)\nameba.db.ebean.support.ModelResourceStructure.executeTx(ModelResourceStructure.java:745)\nameba.db.ebean.support.ModelResourceStructure.executeTx(ModelResourceStructure.java:775)\nameba.db.ebean.support.ModelResourceStructure.insert(ModelResourceStructure.java:156)\nameba.db.ebean.support.AbstractModelResource.insert(AbstractModelResource.java:51)\nsun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\nsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:606)\norg.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)\norg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)\norg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)\norg.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)\norg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)\norg.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)\norg.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)\norg.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)\norg.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)\norg.glassfish.jersey.internal.Errors$1.call(Errors.java:271)\norg.glassfish.jersey.internal.Errors$1.call(Errors.java:267)\norg.glassfish.jersey.internal.Errors.process(Errors.java:315)\norg.glassfish.jersey.internal.Errors.process(Errors.java:297)\norg.glassfish.jersey.internal.Errors.process(Errors.java:267)\norg.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)\norg.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)\norg.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)\nameba.container.grizzly.server.http.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:150)\norg.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)\norg.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)\norg.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)\njava.lang.Thread.run(Thread.java:745)\n",
    "source" : "com.avaje.ebeaninternal.server.persist.BatchedPstmtHolder.flush(BatchedPstmtHolder.java:128)"
  }, {
    "code" : 591275384,
    "message" : "Column 'id' cannot be null",
    "description" : "com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1819)\ncom.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1281)\ncom.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:559)\ncom.avaje.ebeaninternal.server.persist.BatchedPstmt.executeAndCheckRowCounts(BatchedPstmt.java:127)\ncom.avaje.ebeaninternal.server.persist.BatchedPstmt.executeBatch(BatchedPstmt.java:88)\ncom.avaje.ebeaninternal.server.persist.BatchedPstmtHolder.flush(BatchedPstmtHolder.java:95)\ncom.avaje.ebeaninternal.server.persist.BatchControl.flushPstmtHolder(BatchControl.java:198)\ncom.avaje.ebeaninternal.server.persist.BatchControl.executeNow(BatchControl.java:212)\ncom.avaje.ebeaninternal.server.persist.BatchedBeanHolder.executeNow(BatchedBeanHolder.java:93)\ncom.avaje.ebeaninternal.server.persist.BatchControl.flush(BatchControl.java:252)\ncom.avaje.ebeaninternal.server.persist.BatchControl.flush(BatchControl.java:219)\ncom.avaje.ebeaninternal.server.transaction.JdbcTransaction.flushBatch(JdbcTransaction.java:634)\ncom.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.flushJdbcBatchOnQuery(DefaultOrmQueryEngine.java:46)\ncom.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findIds(DefaultOrmQueryEngine.java:58)\ncom.avaje.ebeaninternal.server.core.OrmQueryRequest.findIds(OrmQueryRequest.java:234)\ncom.avaje.ebeaninternal.server.core.DefaultServer.findIdsWithCopy(DefaultServer.java:1270)\ncom.avaje.ebeaninternal.server.core.DefaultServer.findIds(DefaultServer.java:1262)\ncom.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findIds(DefaultOrmQuery.java:938)\ncom.avaje.ebeaninternal.util.DefaultExpressionList.findIds(DefaultExpressionList.java:183)\ncom.sinitek.fiaame.resources.stockresearch.IndustryadviceResource.postInsertModel(IndustryadviceResource.java:138)\ncom.sinitek.fiaame.resources.stockresearch.IndustryadviceResource.postInsertModel(IndustryadviceResource.java:35)\nameba.db.ebean.support.ModelResourceStructure$1.run(ModelResourceStructure.java:161)\nameba.db.ebean.support.ModelResourceStructure$15.call(ModelResourceStructure.java:749)\nameba.db.ebean.support.ModelResourceStructure.processTransactionError(ModelResourceStructure.java:717)\nameba.db.ebean.support.ModelResourceStructure.executeTx(ModelResourceStructure.java:745)\nameba.db.ebean.support.ModelResourceStructure.executeTx(ModelResourceStructure.java:775)\nameba.db.ebean.support.ModelResourceStructure.in...more...
```

**Comment by icode** [comment]
@rbygrave A offline application,  client send UUID entity at network online. So use HTTP `PUT` method, but service has complex business, only new entity need update all properties.

**Comment by rbygrave** [comment]
> update ir_report set create_empid=?, ... id=? where id=?

> Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' cannot be null


So it is trying to do an update and the id specified is null.
