### ISSUE TITLE
ENH: Add EbeanServerFactory.createWithContextClassLoader() to support OSGi

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#305]
Just an update.  It seems in Apache Karaf 3.x, the following error may occur when stopping/starting the OSGi bundle that makes use of a JNDI lookup (from https://issues.apache.org/jira/browse/KARAF-3445 ):

Caused by: javax.naming.NoInitialContextException: Unable to find the InitialContextFactory org.eclipse.jetty.jndi.InitialContextFactory.
at org.apache.aries.jndi.ContextHelper.getInitialContext(ContextHelper.java:148)
at org.apache.aries.jndi.OSGiInitialContextFactoryBuilder.getInitialContext(OSGiInitialContextFactoryBuilder.java:49)
at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)[:1.8.0_45-internal]
at javax.naming.InitialContext.init(InitialContext.java:244)[:1.8.0_45-internal]
at javax.naming.InitialContext.<init>(InitialContext.java:192)[:1.8.0_45-internal]

Here is a workaround specifically for Ebean (when testing 4.7.1-SNAPSHOT) (based on http://mail-archives.apache.org/mod_mbox/karaf-user/201408.mbox/%3C1407791611830-4034697.post@n3.nabble.com%3E ):

ServerConfig config = new ServerConfig();
config.setName(CONFIG_DB_NAME);
config.loadFromProperties(props);
config.setDdlGenerate(false);
config.setDdlRun(false);
config.addClass(Foo.class);
config.setDefaultServer(true);

ClassLoader cl = Thread.currentThread().getContextClassLoader();
Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader());
try {
    server = EbeanServerFactory.create(config);
} catch(Exception ex) {
    String stacktrace = "";
    for (StackTraceElement stackTraceElement : ex.getStackTrace()) {
        stacktrace += stackTraceElement.toString() + "\n";
    }

    log.error("EXCEPTION:\n" + ex.getMessage() + "\n" + stacktrace, ex);
    throw ex;
} finally {
    Thread.currentThread().setContextClassLoader(cl);
}

**Comment by rbygrave** [comment]
So as a fix/enhancement we will add a EbeanServerFactory.createWithContextClassLoader() method that takes a classLoader that can set to be the context class loader during the creation of the EbeanServer.
