### ISSUE TITLE
ScalarTypeConverters for Java8 time datatypes not working

### ISSUE THREAD

**Issue by wjtan** [ebean-orm/avaje-ebeanorm#309]
`jdbcNative` for ScalarTypeConverters for Java8 time datatypes should be false.

I received the following exception when using Java8 time datatypes in query expressions.
````
javax.persistence.PersistenceException: Error with property[2] dt[93]data[2015-06-12T15:38:01.607Z][java.time.Instant]
	at com.avaje.ebeaninternal.server.persist.Binder.bindSimpleData(Binder.java:325)
	at com.avaje.ebeaninternal.server.persist.Binder.bindObject(Binder.java:216)
	at com.avaje.ebeaninternal.server.persist.Binder.bindObject(Binder.java:173)
	at com.avaje.ebeaninternal.server.query.CQueryPredicates.bind(CQueryPredicates.java:157)
	at com.avaje.ebeaninternal.server.query.CQueryRowCount.findRowCount(CQueryRowCount.java:126)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findRowCount(CQueryEngine.java:86)
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findRowCount(DefaultOrmQueryEngine.java:52)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findRowCount(OrmQueryRequest.java:230)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findRowCountWithCopy(DefaultServer.java:1235)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findRowCount(DefaultServer.java:1227)
	at com.avaje.ebeaninternal.server.query.LimitOffsetPagedList.getTotalRowCount(LimitOffsetPagedList.java:92)
	
````

**Comment by rbygrave** [comment]
It seems to me that you have not included the cause exception.  Can you
include the rest of the stack trace?

Cheers, Rob.

**Comment by wjtan** [comment]
Unfortunately, I cannot include the rest of the stack trace. This exception happened when using Java 8 datetime types in the Model.

For example, the Joda `LocalDateTime` defined `jdbcNative` to be [false](https://github.com/ebean-orm/avaje-ebeanorm/blob/master/src/main/java/com/avaje/ebeaninternal/server/type/ScalarTypeJodaLocalDateTime.java#L17). Therefore the [Jdbc type conversion](https://github.com/ebean-orm/avaje-ebeanorm/blob/master/src/main/java/com/avaje/ebeaninternal/server/persist/Binder.java#L169) is called by the Binder during the query.

However, the equivalent Java 8 `LocalDateTime` defined `jdbcNative` to be [true](https://github.com/ebean-orm/avaje-ebeanorm/blob/master/src/main/java/com/avaje/ebeaninternal/server/type/ScalarTypeLocalDateTime.java#L17).

This caused the Binder to [cast the LocalDateTime to Timestamp](https://github.com/ebean-orm/avaje-ebeanorm/blob/master/src/main/java/com/avaje/ebeaninternal/server/persist/Binder.java#L293).

**Comment by rbygrave** [comment]
Yes, I understand now.  Sorry, I didn't quite follow initially.
