### ISSUE TITLE
RawSql fetch object with inheritance

### ISSUE THREAD

**Issue by alex-zykov** [ebean-orm/avaje-ebeanorm#322]
In 4.0.1 it became possible to load abstract objects with inheritance using RawSql. https://github.com/ebean-orm/avaje-ebeanorm/issues/112
```java
    String sql = "select dtype, id, license_number from vehicle where id = :id";
    RawSqlBuilder rawSqlBuilder = RawSqlBuilder.parse(sql);
    
    RawSql rawSql = rawSqlBuilder.create();
    
    List<Vehicle> list = Ebean.find(Vehicle.class)
        .setRawSql(rawSql)
        .setParameter("id", truck.getId())
        .findList();
```

In our case we want to fetch them in the Sql select class. Previously without inheritance we did something like this:
```java
@Entity
@Sql
public class VehicleRatingAggregate {
         @OneToOne
         public Vehicle vehicle;
          
         public Float rating;
}

String sql = "select id, rating from vehicle join ....very long query....";
RawSql rawSql = RawSqlBuilder.unparsed(sql)
        .columnMapping("id","vehicle.id")
        .columnMapping("rating","rating")
        .create(); 
List<VehicleRatingAggregate> vehicleRatingAggregates = Ebean.find(VehicleRatingAggregate.class)
        .setRawSql(rawSql)
        .fetch("vehicle",new FetchConfig().query())
        .findList();
```
And after adding inheritance it surely fails with: `Inheritance type for discriminator value was not found`. Is it feasible to get the same result with inheritance and without global workaround?

**Comment by rbygrave** [comment]
I don't understand yet.  Are you saying that your query that used to work
now fails? ... your RawSql query that loads into VehicleRatingAggregate
does not work now?

**Comment by alex-zykov** [comment]
The query itself is giving the expected result. Fetching (`.fetch("vehicle",new FetchConfig().query())`) with id being mapped (`.columnMapping("id","vehicle.id")`) fails since it is impossible to map the discriminator value manually to make Ebean properly cast a `Vehicle`. So it is possible to load the `id` list itself and make one more query to get everything. I am wondering if there is a lack of functionality to do it with a simple join as I did it before having inheritance or I missed something somewhere.

**Comment by rbygrave** [comment]
So I think your query that was working is now not working and specifically
the 'secondary query' is failing with an error.

*> fails since it is impossible to map the discriminator value manually to
make Ebean properly cast a Vehicle.*

I think Ebean should be able to fire the seconday query with just the id's
... and it should include the discriminator column in that query and hence
be able to determine the inheritance / vehicle type ... so if I have
understood correctly that sounds more like a bug to me.

Can you include more details on the error ...  specifically I would like to
see the SQL for the secondary query (fetching the vehicle's by id) and
check that the dtype column is included in the SQL that Ebean is generating
for that.

At the moment this looks like a bug to me though.

**Comment by alex-zykov** [comment]
It fails after the primary and before secondary query.
The stack trace:
```
01:16:31.221 [main] TRACE org.avaje.ebean.SQL - txn[1011] select type, id from parent where number > 1; --bind()
01:16:31.224 [main] TRACE org.avaje.ebean.TXN - txn[1011] Commit - query only

javax.persistence.PersistenceException: Error loading on org.example.domain.ParentAggregate.parent
	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:88)
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne.load(BeanPropertyAssocOne.java:544)
	at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:236)
	at com.avaje.ebeaninternal.server.query.CQuery.readRow(CQuery.java:497)
	at com.avaje.ebeaninternal.server.query.CQuery.readBeanInternal(CQuery.java:524)
	at com.avaje.ebeaninternal.server.query.CQuery.hasNextBean(CQuery.java:637)
	at com.avaje.ebeaninternal.server.query.CQuery.readTheRows(CQuery.java:629)
	at com.avaje.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:595)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:176)
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:80)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:284)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1367)
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:933)
	at org.example.domain.ParentRawSqlTest.RawSqlParentFetch(ParentRawSqlTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
Caused by: javax.persistence.PersistenceException: Inheritance type for discriminator value [3] was not found?
	at com.avaje.ebeaninternal.server.deploy.InheritInfo.readType(InheritInfo.java:202)
	at com.avaje.ebeaninternal.server.deploy.InheritInfo.readType(InheritInfo.java:188)
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne$Reference.read(BeanPropertyAssocOne.java:670)
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne.read(BeanPropertyAssocOne.java:516)
	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:77)
	... 34 more
```
Also did a test project trying to play around: https://github.com/alex-zykov/abstract-inheritance-ebean-example

**Comment by rbygrave** [comment]
*> Inheritance type for discriminator value [3] was not found?*

That "3" does not look valid, should be "A" or "B". I should be able to look
into this later today but yes that looks like a bug at this stage.


Cheers, Rob.

**Comment by rbygrave** [comment]
Ok, I have a handle on the issue.  We need to support both scenarios ... #112 and this one.  I think I have a mechanism that will do it ...

**Comment by rbygrave** [comment]
So with this fix there are 2 options:

Option 1 : ignore the discriminator column
```java
    RawSql rawSql = RawSqlBuilder
        .unparsed("select type, id from rawinherit_parent where number > 1")
        .columnMappingIgnore("type") // can ignore the discriminator 'type'
        .columnMapping("id", "parent.id")
        .create();
```

Option 2: map the discriminator column
```java
    RawSql rawSql = RawSqlBuilder
        .unparsed("select type, id from rawinherit_parent where number > 1")
        .columnMapping("type", "parent.type") // can map the discriminator column 'type'
        .columnMapping("id", "parent.id")
        .create();
```

Refer to the test ParentRawSqlTest which is now in com.avaje.tests.rawsql.inherit.ParentRawSqlTest

Cheers, Rob.

**Comment by alex-zykov** [comment]
Thank you for quick response and fix.

**Comment by rbygrave** [comment]
As a usage note ... the discriminator column is placed first and just before the id column.
