### ISSUE TITLE
RawSql issue with inheritance - PersistenceException: Inheritance type for discriminator value 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#416]
```java
query.setRawSql(RawSqlBuilder.unparsed("select" +
		" ScheduledAssignments.scheduledAssignmentId," +
		" Roles.roleTypeId," +
		" Roles.roleId," +
		//" Roles.name as roleName," +
		" ScheduledAssignments.userId" +
		" from ScheduledAssignments" +
		" join Roles on Roles.roleId = ScheduledAssignments.roleId" +
		" join Users on Users.userId = ScheduledAssignments.userId" +
		" where ScheduledAssignments.scheduledAssignmentId = " + sa.getId()
		)
		.columnMapping("scheduledAssignmentId", "id")
		.columnMapping("roleTypeId", "role.roletypeid")
		.columnMapping("roleId", "role.id")
		//.columnMapping("roleName", "role.name")
		.columnMapping("userId", "user.id")
		.create());

```

This works as-is. If you uncomment those 2 lines it fails with this:

javax.persistence.PersistenceException: Inheritance type for discriminator value [170] was not found?
	at com.avaje.ebeaninternal.server.deploy.InheritInfo.readType(InheritInfo.java:202)
	at com.avaje.ebeaninternal.server.deploy.InheritInfo.readType(InheritInfo.java:188)
	at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:210)
	at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:296)

170 is a roleId. Should I not be able to select and map properties of a relation when said relation requires a discriminator? The "name" property is in the super class, but I tried a different property in the subclass with the same result.

**Comment by rbygrave** [comment]
Effectively the fix here was in SqlTreeNodeBean buildRawSqlSelectChain() to add the discriminator property to the select chain (as it is required and must immediately proceed the id column in order to determine the inheritance type prior to reading/building the bean).

That means that CQueryPlanRawSql now no longer tries to add the discriminator into the indexPositions array (as the select chain now always contains the discriminator).
