### ISSUE TITLE
Review JodaLocalTime (being stored and fetched using UTC) 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#420]
It looks like a bug in JodaLocalTime as per discussion https://groups.google.com/forum/#!topic/ebean/S1OSrsN8fCs

> In my opinion, a LocalTime is timezone-less, so 07:00:00 must be and stay 07:00:00 until it is placed in some calendar or other meaningful representation.

Rob: Yes I agree with that.  At this stage I can see the difference in implementation and I can see the argument for ScalarTypeJodaLocalTime being less correct.

**Comment by rbygrave** [comment]
So with this fix ... Ebean will now throw an exception if you try to use a Joda LocalTime and have not set ServerConfig.jodaLocalTimeMode to be either 'utc' or 'normal'.

Moving forward I expect people to choose 'normal' and for users with existing UTC based LocalTime stored then they would choose 'utc' as the mode.  Anyone using java8 time's LocalTime has always been storing as local timezone values (not UTC).

In ebean properties you can

ebean.jodaLocalTimeMode=normal
#ebean.jodaLocalTimeMode=utc


And the stack trace you get if you don't configure one of the above is:


Caused by: java.lang.IllegalStateException: ScalarType of Joda LocalTime not defined. You need to set ServerConfig.jodaLocalTimeMode to either 'normal' or 'utc'.  UTC is the old mode using UTC timezone but local time zone is now preferred as 'normal' mode.
	at com.avaje.ebeaninternal.server.type.DefaultTypeManager.getScalarType(DefaultTypeManager.java:290)
	at com.avaje.ebeaninternal.server.deploy.parse.DeployCreateProperties.createProp(DeployCreateProperties.java:259)
	at com.avaje.ebeaninternal.server.deploy.parse.DeployCreateProperties.createProp(DeployCreateProperties.java:316)
	at com.avaje.ebeaninternal.server.deploy.parse.DeployCreateProperties.createProperties(DeployCreateProperties.java:109)
	... 40 more
