### ISSUE TITLE
Delete bean with unloaded version property throws OptimisticLockException

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#467]
```java
    // delete by by without version loaded ... should not throw OptimisticLockException
    Contact ref = Ebean.getReference(Contact.class, 999999);
    Ebean.delete(ref);
```

```console
14:58:59.028 [main] DEBUG org.avaje.ebean.SQL - txn[1003] delete from contact where id=?; --bind(999999,)
14:58:59.029 [main] DEBUG org.avaje.ebean.SUM - txn[1003] OptimisticLockException:Data has changed. updated [0] rows sql[delete from contact where id=?] bind[999999,]
```

javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[delete from contact where id=?] bind[999999,]

	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:91)
	at com.avaje.ebeaninternal.server.persist.dml.DeleteHandler.execute(DeleteHandler.java:51)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:73)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:41)

**Comment by rbygrave** [comment]
This is not really "breaking-api" but an API change as 2 delete() methods on EbeanServer now return boolean (and matching delete() methods on Model also now return boolean).
