### ISSUE TITLE
IllegalStateException: No CurrentUserProvider has been set so @WhoCreated is not supported

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#474]
```
ERROR c.a.e.s.deploy.BeanDescriptorManager - Error in deployment
java.lang.RuntimeException: Error reading annotations for com.sinitek.fiaame.models.common.ZGJSetting
   at com.avaje.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:58) ~[avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createDeployBeanInfo(BeanDescriptorManager.java:1037) ~[avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentInitial(BeanDescriptorManager.java:533) ~[avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:280) ~[avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:129) [avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:124) [avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:41) [avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108) [avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67) [avaje-ebeanorm-6.10.4.jar:na]
   at ameba.db.ebean.EbeanFeature.configure(EbeanFeature.java:269) [ameba-0.1.7-20151124.110029-300.jar:0.1.7-SNAPSHOT]
   at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:714) [jersey-common-2.22.1.jar:na]
   at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:644) [jersey-common-2.22.1.jar:na]
   at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:829) [jersey-server-2.22.1.jar:na]
   at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:453) [jersey-server-2.22.1.jar:na]
   at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184) [jersey-server-2.22.1.jar:na]
   at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350) [jersey-server-2.22.1.jar:na]
   at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347) [jersey-server-2.22.1.jar:na]
   at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.22.1.jar:na]
   at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.22.1.jar:na]
   at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) [jersey-common-2.22.1.jar:na]
   at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347) [jersey-server-2.22.1.jar:na]
   at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:311) [jersey-server-2.22.1.jar:na]
   at ameba.container.grizzly.server.http.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:96) [ameba-container-grizzly-0.1.7.Alpha1.jar:na]
   at ameba.container.grizzly.server.http.GrizzlyHttpContainerProvider.createContainer(GrizzlyHttpContainerProvider.java:18) [ameba-container-grizzly-0.1.7.Alpha1.jar:na]
   at org.glassfish.jersey.server.ContainerFactory.createContainer(ContainerFactory.java:81) [jersey-server-2.22.1.jar:na]
   at ameba.container.grizzly.server.GrizzlyContainer.configureHttpContainer(GrizzlyContainer.java:209) [ameba-container-grizzly-0.1.7.Alpha1.jar:na]
   at ameba.container.Container.<init>(Container.java:45) [ameba-0.1.7-20151124.110029-300.jar:0.1.7-SNAPSHOT]
   at ameba.container.grizzly.server.GrizzlyContainer.<init>(GrizzlyContainer.java:75) [ameba-container-grizzly-0.1.7.Alpha1.jar:na]
   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.7.0_67]
   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [na:1.7.0_67]
   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.7.0_67]
   at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [na:1.7.0_67]
   at ameba.container.Container.create(Container.java:64) [ameba-0.1.7-20151124.110029-300.jar:0.1.7-SNAPSHOT]
   at ameba.Ameba.bootstrap(Ameba.java:165) [ameba-0.1.7-20151124.110029-300.jar:0.1.7-SNAPSHOT]
   at ameba.Ameba.bootstrap(Ameba.java:150) [ameba-0.1.7-20151124.110029-300.jar:0.1.7-SNAPSHOT]
   at ameba.Ameba.main(Ameba.java:116) [ameba-0.1.7-20151124.110029-300.jar:0.1.7-SNAPSHOT]
   at com.sinitek.fiaame.Main.main(Main.java:10) [test-classes/:na]
Caused by: java.lang.IllegalStateException: No CurrentUserProvider has been set so @WhoCreated is not supported
   at com.avaje.ebeaninternal.server.deploy.generatedproperty.GeneratedPropertyFactory.setWhoCreated(GeneratedPropertyFactory.java:76) ~[avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.deploy.parse.AnnotationFields.readField(AnnotationFields.java:197) ~[avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.deploy.parse.AnnotationFields.parse(AnnotationFields.java:69) ~[avaje-ebeanorm-6.10.4.jar:na]
   at com.avaje.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:55) ~[avaje-ebeanorm-6.10.4.jar:na]
   ... 36 common frames omitted
```

base model
```java
@MappedSuperclass
public abstract class BaseModel extends Model implements CurrentUserProvider {
   @Id
   @GeneratedValue
   public Long id;
   @CreatedTimestamp
   public Timestamp createTime;
   @UpdatedTimestamp
   public Timestamp updateTime;
   /**
    * empid
    */
   @WhoCreated
   public Integer createEmpid;

   @WhoModified
   public Integer updateEmpid;

   @Override
   public Object currentUser() {
       Subject subject = SecurityUtils.getSubject();
       if (subject.isAuthenticated() || subject.isRemembered()) {
           AbstractSession session = Session.get();
           if (session != null) {
               User user = session.getAttribute("user");
               if (user == null) {
                   user = User.<Long, User>withFinder().where().eq("username", subject.getPrincipal()).findUnique();
                   session.setAttribute("user", user);
               }
               if (user != null) {
                   return user.id;
               }
           }
       }
       return null;
   }
}
```

```java
class ZGJSetting extends BaseModel {}
```

**Comment by rbygrave** [comment]
You need to set the CurrentUserProvider implementation to the ServerConfig programmatically or via ebean.properties

```java
CurrentUserProvider currentUser = ....

serverConfig.setCurrentUserProvider(currentUser)
```

or

ebean.currentUserProvider=somepackage.MyCurrentUserProviderImplemenation

**Comment by rbygrave** [comment]
That should do it. Will close for now.
