### ISSUE TITLE
@EnumValue is being trimmed, may result in unexpected behaviour with CHAR columns for some database systems

### ISSUE THREAD

**Issue by spiltcoffee** [ebean-orm/avaje-ebeanorm#496]
The following test was written using ebean-orm/avaje-ebeanorm-examples/a-basic as the project.

Let's say that I'm using PostgresSQL for my database. I start with the following enum and model.

* __DayOfWeek.java__
  ```java
  package org.example.domain;

  import com.avaje.ebean.annotation.EnumValue;

  public enum DayOfWeek {
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
    SUNDAY
  }
```
* __Price.java__
  ```java
  package org.example.domain;

  import javax.persistence.*;

  @Entity
  @Table(name="o_price")
  public class Price extends BaseModel {

    double price;

    @Enumerated(EnumType.STRING)
    @Column(columnDefinition="char(9)")
    DayOfWeek day;

    public double getPrice() {
      return this.price;
    }

    public void setPrice(double price) {
      this.price = price;
    }

    public DayOfWeek getDay() {
      return this.day;
    }

    public void setDay(DayOfWeek day) {
      this.day = day;
    }
  }
```

... and I write something that tries to get a Price from my database...
* __EnumValueCharTest.java__
  ```java
  package main;

  import com.avaje.ebean.Ebean;
  import com.avaje.ebean.EbeanServer;
  import com.avaje.ebean.TxRunnable;
  import org.example.domain.DayOfWeek;
  import org.example.domain.Price;
  import org.junit.Test;

  public class EnumValueCharTest {

    @Test
    public void simple() {
      final EbeanServer server = Ebean.getServer(null);

      server.execute(new TxRunnable() {
        public void run() {
          server.createUpdate(Price.class, "delete from Price").execute();

          Price pMonday = new Price();
          pMonday.setPrice(14.95);
          pMonday.setDay(DayOfWeek.MONDAY);
          server.save(pMonday);

          Price pWednesday = new Price();
          pWednesday.setPrice(12.95);
          pWednesday.setDay(DayOfWeek.WEDNESDAY);
          server.save(pWednesday);
        }
      });

      server.createQuery(Price.class).findList();
    }
  }
```
I get an error back from Ebean.
```
javax.persistence.PersistenceException: Error loading on org.example.domain.Price.day

	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:85)
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.load(BeanProperty.java:527)
	at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:268)
	at com.avaje.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:426)
	at com.avaje.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:506)
	at com.avaje.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:537)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:302)
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:94)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:280)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1430)
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1017)
	at main.EnumValueCharTest.simple(EnumValueCharTest.java:18)
Caused by: java.lang.IllegalArgumentException: No enum constant org.example.domain.DayOfWeek.MONDAY   
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.avaje.ebeaninternal.server.type.ScalarTypeEnumStandard$EnumBase.parse(ScalarTypeEnumStandard.java:221)
	at com.avaje.ebeaninternal.server.type.ScalarTypeEnumStandard$StringEnum.read(ScalarTypeEnumStandard.java:93)
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.read(BeanProperty.java:539)
	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:74)
	... 32 more
```
(If you can't figure this one out, it's because "MONDAY   " is not a value of DayOfWeek)

Okay, so, that's annoying but also understandable. Surely I can work around this issue by using EnumValue instead?

* __DayOfWeek.java (changed)__
  ```java
  package org.example.domain;

  import com.avaje.ebean.annotation.EnumValue;

  public enum DayOfWeek {
    @EnumValue("MONDAY   ") MONDAY,
    @EnumValue("TUESDAY  ") TUESDAY,
    @EnumValue("WEDNESDAY") WEDNESDAY,
    @EnumValue("THURSDAY ") THURSDAY,
    @EnumValue("FRIDAY   ") FRIDAY,
    @EnumValue("SATURDAY ") SATURDAY,
    @EnumValue("SUNDAY   ") SUNDAY
  }
```

Well, no, I still get an error. A different one, though.
```
javax.persistence.PersistenceException: Error loading on org.example.domain.Price.day

	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:85)
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.load(BeanProperty.java:527)
	at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:268)
	at com.avaje.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:426)
	at com.avaje.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:506)
	at com.avaje.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:537)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:302)
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:94)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:280)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1430)
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1017)
	at main.EnumValueCharTest.simple(EnumValueCharTest.java:18)
Caused by: java.lang.IllegalArgumentException: Bean value for MONDAY    not found in {WEDNESDAY=WEDNESDAY, MONDAY=MONDAY, THURSDAY=THURSDAY, SUNDAY=SUNDAY, TUESDAY=TUESDAY, FRIDAY=FRIDAY, SATURDAY=SATURDAY}
	at com.avaje.ebeaninternal.server.type.EnumToDbValueMap.getBeanValue(EnumToDbValueMap.java:123)
	at com.avaje.ebeaninternal.server.type.EnumToDbStringMap.read(EnumToDbStringMap.java:40)
	at com.avaje.ebeaninternal.server.type.ScalarTypeEnumWithMapping.read(ScalarTypeEnumWithMapping.java:71)
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.read(BeanProperty.java:539)
	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:74)
	... 32 more
```

It looks like the strings passed into @EnumValue are trimmed at some point, so they do not match my untrimmed PostgreSQL strings that I get back.

Is this a bug, or is there a way to prevent Ebean from performing a trim on @EnumValue unless I want it?

As an aside, this test worked fine when using the H2 database - seems like it doesn't bother padding CHAR fields.

**Comment by rbygrave** [comment]
Do you have a case where you have such a char column in a production db?

The ddl generated by ebean should be a varchar (not char). Hmmm.

Thanks, Rob.

**Comment by spiltcoffee** [comment]
Unfortunately, yes.

In my case I'm not using a DDL auto regeneration from my database objects, but rather building my database objects based off an existing DDL.

The DDL used in the example was just to make the example work. :p

**Comment by rbygrave** [comment]
Right. There might be 2 options for handling this. We just need to be
careful with existing users etc.

I should be able to look at it in 2 days (my Monday).

Cheers, Rob.

**Comment by rbygrave** [comment]
Ok, I'm happy enough that we can treat this as a bug.  That is, with @EnumValue we should NOT trim() the values specified (which we are doing prior to this fix) and that space padding put into an @EnumValue should be treated as significant.

This means the "Fix" is to not trim() the string values from the @EnumValue ... so the space padding on "MONDAY   " is left on and not trimmed off internally by Ebean.
