### ISSUE TITLE
@OneToOne with @JoinColumn to non primary key throws `Data conversion error`

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#529]
```java
import com.avaje.ebean.EbeanServer;
import com.avaje.ebean.EbeanServerFactory;
import com.avaje.ebean.config.DataSourceConfig;
import com.avaje.ebean.config.ServerConfig;
import com.google.common.collect.Lists;
import org.avaje.agentloader.AgentLoader;
import org.h2.Driver;
import org.junit.Before;
import org.junit.Test;

import javax.persistence.*;
import java.io.IOException;
import java.lang.instrument.IllegalClassFormatException;

/**
 * @author icode
 */
public class EbeanTest {
    EbeanServer server;

    @Before
    public void init() {
        AgentLoader.loadAgentFromClasspath("avaje-ebeanorm-agent", "debug=5");
        final ServerConfig config = new ServerConfig();
        config.setClasses(Lists.<Class<?>>newArrayList(RoadShowMsg.class, Company.class));
        DataSourceConfig dataSourceConfig = new DataSourceConfig();
        dataSourceConfig.setUrl("jdbc:h2:file:./db");
        dataSourceConfig.setDriver(Driver.class.getName());
        dataSourceConfig.setUsername("sa");
        dataSourceConfig.setPassword("");
        config.setDataSourceConfig(dataSourceConfig);
        config.setName("default");
        config.setDdlGenerate(true);
        config.setDdlRun(true);
        config.setDefaultServer(true);
        server = EbeanServerFactory.create(config);
    }

    @Test
    public void JsonTest() throws IOException, IllegalClassFormatException, ClassNotFoundException {
        RoadShowMsg msg = new RoadShowMsg();
        Company company = new Company();
        company.setCorpId("corp_id_1000000");
        msg.setCompany(company);
        server.save(msg);
        server.find(RoadShowMsg.class, 1);
    }

    @MappedSuperclass
    public static abstract class Model {
        @Id
        @GeneratedValue
        public Long id;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }
    }

    @Entity
    public static class RoadShowMsg extends Model {
        @OneToOne(cascade = CascadeType.ALL, optional = false)
        @JoinColumn(name = "corp_id", nullable = false, referencedColumnName = "corp_id")
        public Company company;

        public Company getCompany() {
            return company;
        }

        public void setCompany(Company company) {
            this.company = company;
        }
    }

    @Entity
    public static class Company extends Model {
        @Column(length = 50, unique = true)
        public String corpId;

        public String getCorpId() {
            return corpId;
        }

        public void setCorpId(String corpId) {
            this.corpId = corpId;
        }
    }
}
```

console:
```
javax.persistence.PersistenceException: Error loading on EbeanTest$RoadShowMsg.company

	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:85)
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne.load(BeanPropertyAssocOne.java:615)
	at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:268)
	at com.avaje.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:431)
	at com.avaje.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:512)
	at com.avaje.ebeaninternal.server.query.CQuery.readBean(CQuery.java:494)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:356)
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:129)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:251)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1190)
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1048)
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1035)
	at EbeanTest.JsonTest(EbeanTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
Caused by: org.h2.jdbc.JdbcSQLException: Data conversion error converting "corp_id_1000000" [22018-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.Value.convertTo(Value.java:902)
	at org.h2.value.Value.getLong(Value.java:443)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:650)
	at com.avaje.ebeaninternal.server.type.RsetDataReader.getLong(RsetDataReader.java:121)
	at com.avaje.ebeaninternal.server.type.ScalarTypeLong.read(ScalarTypeLong.java:34)
	at com.avaje.ebeaninternal.server.type.ScalarTypeLong.read(ScalarTypeLong.java:17)
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.read(BeanProperty.java:581)
	at com.avaje.ebeaninternal.server.deploy.id.IdBinderSimple.read(IdBinderSimple.java:177)
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne$Reference.read(BeanPropertyAssocOne.java:749)
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne.read(BeanPropertyAssocOne.java:574)
	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:74)
	... 34 more
Caused by: java.lang.NumberFormatException: For input string: "corp_id_1000000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.h2.value.Value.convertTo(Value.java:854)
	... 44 more
```

**Comment by rbygrave** [comment]
The @JoinColumn uses "corp_id" column which is not the primary key.  That would generally be  deemed a mistake ... so I wonder why "corp_id" is chosen as the join column?

**Comment by icode** [comment]
but JPA @JoinColumn can be use for not primary key.

**Comment by rbygrave** [comment]
Sure, but you didn't answer my question.  Specifically - why "corp_id" is chosen as the join column and not the primary key?

**Comment by icode** [comment]
I don't know, this is my team other member happen.  This is not bug?

**Comment by rbygrave** [comment]
> This is not bug?

This is a case of ... just because you *can* doesn't mean you *should*.

This might be a bug in that - SQL allows joins on arbitrary columns that match by type (which is good/fine from a SQL perspective). JPA @JoinColumn similarly always a join on arbitrary columns that match by type ... with the assumption that the developer is doing the correct thing.

However, you should understand that a numeric primary key column is usually preferred as the join column over a varchar(50) column because the primary key index is usually physically smaller and 'hotter' in the databases caches.

So the join is likely to be sub-optimal and the hope is that was done this way using "corp_id" for a good reason and not simply a mistake.

**Comment by icode** [comment]
em, if this is not bug please throw a explicit error, a clear error. but i think @JoinColumn should on none(not)  primary key

**Comment by rbygrave** [comment]
JPA Spec 11.1.21 
Support for referenced columns that are not primary key columns of the referenced table is optional.
Applications that use such mappings will not be portable.

So this is optional for JPA providers.

Also note: http://stackoverflow.com/questions/5818373/does-the-jpa-specification-allow-references-to-non-primary-key-columns

Now in terms of Ebean ORM internals ... the issue here in trying to support a JoinColumn to a non-primary key is in 2 main areas:
- Loading check against the persistence context (which is @Id / primary key based)
- Support for lazy loading (which is @Id / primary key based)

To support unique non-null columns equally with primary key we need to translate between the unique column and the primary key value for both of those features (the persistence context check and the further lazy loading).  

That has the potential to be "not good implementation" without introducing some level of compromise (separate treatment in persistence context for example).

Ultimately this this mapping option (if supported) there are now 2 active values used to identify each Company instance (the @Id and corpId) and that translates into a combination of extra complexity, performance costs or compromising functionality.

**Comment by rbygrave** [comment]
The best initial response is to treat this as a mapping issue / limitation - that the JoinColumn should map to the primary key (and keep all the internals simple for persistence context checks and lazy loading).

If someone needs this mapping support they can push their case.

**Comment by icode** [comment]
Ebean a lot of annotions not be portable

**Comment by rbygrave** [comment]
If you want to push the case for supporting this mapping you are welcome to voice that.

In JPA this is optional - it seems this mapping is likely only support by Hibernate (not portable to Eclipselink). If you disagree or want to push the case for inclusion by all means do so.

**Comment by rbygrave** [comment]
> Ebean a lot of annotions not be portable

Utlimately that will not be the case. Ebean will support all the JPA mappings according to the spec but note that some of the JPA spec is optional and this is the case because there are differences of opinion as to the true cost / benefit of certain mappings.

Ebean will get there in time but JPA2 mapping is not currently the top priority based on funding etc. If someone wished to fund the push to JPA2 mapping sooner that would be good.

**Comment by rbygrave** [comment]
So the current resolution for this issue is to throw an exception regarding the current limitation of mapping JoinColumn to the primary key. 

This results in an exception of the form:
19:40:31.826 [main] ERROR c.a.e.s.deploy.BeanDescriptorManager - Error in deployment
javax.persistence.PersistenceException: Mapping limitation - @OneToOne @JoinColumn needs to map to a primary key as per Issue #529  - joining to corp_id and not id
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne.initialise(BeanPropertyAssocOne.java:110) ~[classes/:na]

People are welcome to push for the removal of this limitation, in doing so it would be good to indicate if you have thoughts in terms of how to deal with the issues of:
- checking values against the persistence context via both @Id and the unique key value
- adjusting the meaning of "reference bean" in terms of lazy loading for both find by id and find by unique key

Thanks, Rob.

**Comment by almothafar** [comment]
@rbygrave just to revisit this, can't we have something like `@NaturalId`?
https://vladmihalcea.com/how-to-map-a-manytoone-association-using-a-non-primary-key-column/
https://vladmihalcea.com/the-best-way-to-map-a-naturalid-business-key-with-jpa-and-hibernate/
https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/annotations/NaturalId.html

**Comment by rbygrave** [comment]
The first link has nothing to do with `@NaturalId`.  This issue doesn't have much to do with `@NaturalId` either actually (it's about the join column).

Ebean already has support for use of natural key with L2 caching via `@Cache(naturalKey=) ` - https://ebean.io/docs/features/l2cache/bean-cache

With Ebean we do not need our query to change to use the natural key. Ebean detects when the naturalKey is being used in queries and automatically uses the natural key cache as necessary.

**Comment by almothafar** [comment]
@rbygrave Sorry that I didn't read the whole thread, what I was trying to do is that I got something like:

```java
@Entity
@EntityListeners(PreventAnyUpdate.class)
@Table(name = "Labs", schema = "dbo")
public class LabData extends BaseModel<LabData> {
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "LabID", nullable = false, unique = true)
    private Integer id;

    @Id
    @Column(name = "LabCode", nullable = false, unique = true, updatable = false, length = 50)
    private String labCode;
}
```

and 
```java
@Entity
@EntityListeners(PreventAnyUpdate.class)
@Table(name = "LabProjects", schema = "dbo", uniqueConstraints = {@UniqueConstraint(columnNames = {"LabCode", "ProjectID"})})
public class LabProjectData extends BaseModel<LabProjectData> {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "LPID")
    private Long id;

    @ManyToOne(optional = false, targetEntity = LabData.class)
    @JoinColumn(name = "LabCode", referencedColumnName = "LabCode", nullable = false)
    private LabData lab;
}

so that `LabCode` is the real connection with all related tables like the project table, but the problem that the Lab table itself got just an identity column with auto-increment id, when I tried to move `@Id` to `private Integer id` an error showed to me mentioning this item so that why I added a reply, but for now my workaround for it to add that `@Id` to ` private String labCode;` 

Also, I saw the same issue is solved in Hibernate as the links I posted above, that's why I rushed to add my comment to this issue here.

**Comment by rbygrave** [comment]
Ok I see.  We should probably create a new issue and see if it is something we should fix.

Noting that doing _lots_ of joining on a varchar(50) vs joining on an integer could show an interesting performance difference and difference in sizes of indexes so that would be something to be wary of.

**Comment by almothafar** [comment]
@rbygrave Well, I have already a database with a lot of tables and millions of rows of old systems that got a lot of issues that I can't fix, so I try to make my best to implement something or add my fixes (like missing indexes that almost does not exist even foreign keys are also not there).

The fun part is that the real data of `varchar(50)` are just numbers, without leading zeros, but I can't change that as it is a big part that is used almost everywhere.

**Comment by deverlex** [comment]
> Ok I see. We should probably create a new issue and see if it is something we should fix.
> 
> Noting that doing _lots_ of joining on a varchar(50) vs joining on an integer could show an interesting performance difference and difference in sizes of indexes so that would be something to be wary of.

@rbygrave sorry, is the issue fixed?

**Comment by deverlex** [comment]
oh, I have a issue with @EmbeddedId with RawSql mapping
