### ISSUE TITLE
Bean lazy loading can execute an extra query when one of the lazy loaded beans has been deleted 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#535]
So in batch lazy loading of beans, if a bean has actually been deleted it will have a 'lazyLoadFailed' flag set and throw a EntityNotFoundException when accessed. If the bean is not the first bean in the batch then the exception is still thrown but an extra sql query is executed (and that extra query should not really execute).

This bug fix stops that extra query from being executed.

**Comment by rbygrave** [comment]
As part of this fix the EntityNotFoundException is being enhanced that that it states the bean type and Id value of the bean that failed lazy loading.

An example stack trace now is:

javax.persistence.EntityNotFoundException: Lazy loading failed on type:com.avaje.tests.model.basic.UUOne id:9707dd99-3357-4e02-93a6-878486f09e8b - Bean has been deleted
	at com.avaje.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:763)
	at com.avaje.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:747)
	at com.avaje.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:834)
	at com.avaje.tests.model.basic.UUOne._ebean_get_name(UUOne.java:6)
	at com.avaje.tests.model.basic.UUOne.getName(UUOne.java:32)
	...

**Comment by rbygrave** [comment]
In addition as soon as this state is detected then an INFO level message is logged so this is visible in the logs - the exception is only thrown when a bean in this state is accessed/used.

The log message looks like:

20:47:56.282 [main] INFO  c.a.e.api.LoadBeanRequest - Lazy loading unsuccessful for type:UUOne id:9707dd99-3357-4e02-93a6-878486f09e8b - expecting when bean has been deleted
