### ISSUE TITLE
Change PersistenceException: Mapping limitation on @JoinColumn such that it includes the bean type

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#537]
like this
``` 
21:56:38.453 [main] ERROR c.a.e.s.deploy.BeanDescriptorManager - Error in deployment
javax.persistence.PersistenceException: Mapping limitation - @OneToOne @JoinColumn needs to map to a primary key as per Issue #529  - joining to type_id and not id
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocOne.initialise(BeanPropertyAssocOne.java:110) ~[avaje-ebeanorm-6.16.1.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.initialiseOther(BeanDescriptor.java:629) ~[avaje-ebeanorm-6.16.1.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.initialiseAll(BeanDescriptorManager.java:433) ~[avaje-ebeanorm-6.16.1.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:312) ~[avaje-ebeanorm-6.16.1.jar:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:130) [avaje-ebeanorm-6.16.1.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:122) [avaje-ebeanorm-6.16.1.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:42) [avaje-ebeanorm-6.16.1.jar:na]
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108) [avaje-ebeanorm-6.16.1.jar:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67) [avaje-ebeanorm-6.16.1.jar:na]
	at ameba.db.ebean.EbeanFeature.configure(EbeanFeature.java:173) [ameba-0.1.8-20160121.132952-82.jar:0.1.8-SNAPSHOT]
	at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:714) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:644) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:829) [jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:453) [jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184) [jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350) [jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347) [jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347) [jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:311) [jersey-server-2.22.1.jar:na]
	at ameba.container.grizzly.server.http.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:105) [ameba-container-grizzly-0.1.8-20160114.195308-7.jar:na]
	at ameba.container.grizzly.server.http.GrizzlyHttpContainerProvider.createContainer(GrizzlyHttpContainerProvider.java:18) [ameba-container-grizzly-0.1.8-20160114.195308-7.jar:na]
	at org.glassfish.jersey.server.ContainerFactory.createContainer(ContainerFactory.java:81) [jersey-server-2.22.1.jar:na]
	at ameba.container.grizzly.server.GrizzlyContainer.configureHttpContainer(GrizzlyContainer.java:213) [ameba-container-grizzly-0.1.8-20160114.195308-7.jar:na]
	at ameba.container.Container.<init>(Container.java:45) [ameba-0.1.8-20160121.132952-82.jar:0.1.8-SNAPSHOT]
	at ameba.container.grizzly.server.GrizzlyContainer.<init>(GrizzlyContainer.java:77) [ameba-container-grizzly-0.1.8-20160114.195308-7.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.7.0_80]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [na:1.7.0_80]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.7.0_80]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [na:1.7.0_80]
	at ameba.container.Container.create(Container.java:64) [ameba-0.1.8-20160121.132952-82.jar:0.1.8-SNAPSHOT]
	at ameba.Ameba.bootstrap(Ameba.java:166) [ameba-0.1.8-20160121.132952-82.jar:0.1.8-SNAPSHOT]
	at ameba.Ameba.bootstrap(Ameba.java:150) [ameba-0.1.8-20160121.132952-82.jar:0.1.8-SNAPSHOT]
	at ameba.Ameba.main(Ameba.java:116) [ameba-0.1.8-20160121.132952-82.jar:0.1.8-SNAPSHOT]
	at com.sinitek.fiaame.Main.main(Main.java:10) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
	at com.intellij.uiDesigner.snapShooter.SnapShooter.main(SnapShooter.java:59) [uiDesigner.jar:na]
```

# I find it difficult to find the model

**Comment by rbygrave** [comment]
Right, I'll look to change the exception message such that it contains the entity bean type.

**Comment by rbygrave** [comment]
For example:

Caused by: java.lang.RuntimeException: javax.persistence.PersistenceException: Mapping limitation - @JoinColumn on com.avaje.tests.model.onetoone.ORoadShowMsg.company needs to map to a primary key as per Issue #529  - joining to corp_id and not id
