### ISSUE TITLE
Regression: ArrayIndexOutOfBoundsException when lazy loading on bean with inheritance

### ISSUE THREAD

**Issue by dastultz** [ebean-orm/avaje-ebeanorm#549]
Hi Rob, it looks like 6.16.2 has a regression. When I run a unit test and there is no `ebean-autoTune.xml` file present I get the following exception. When I place a populated or essentially empty file (no origin elements) there the test passes. The test passes with 6.16.1 whether the autoTune file is present or not.

```
java.lang.ArrayIndexOutOfBoundsException: 42
    at com.avaje.ebean.bean.EntityBeanIntercept.isLoadedProperty(EntityBeanIntercept.java:495)
    at com.avaje.ebean.bean.EntityBeanIntercept.isLazyLoadFailure(EntityBeanIntercept.java:356)
    at com.avaje.ebeaninternal.api.LoadBeanRequest.postLoad(LoadBeanRequest.java:162)
    at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:219)
    at com.avaje.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:501)
    at com.avaje.ebeaninternal.server.loadcontext.DLoadBeanContext$LoadBuffer.loadBean(DLoadBeanContext.java:194)
    at com.avaje.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:774)
    at com.avaje.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:747)
    at com.avaje.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:834)
    at com.opentempo.webapp.modeleb.Block._ebean_get_cases(Block.java:1)
    at com.opentempo.webapp.modeleb.Block.getCases(Block.java:25)
```

**Comment by dastultz** [comment]
Looks like I was wrong about the empty auto tune file (not really empty but with no origins). Must have gotten my unit test file confused with my webapp file.

**Comment by rbygrave** [comment]
Has Block got an inheritance hierarchy?

**Comment by rbygrave** [comment]
Ok good - I've created a failing test case by lazy loading on a specific property in an inheritance hierarchy .  I've identified the error in the logic so looking to fix that.

java.lang.ArrayIndexOutOfBoundsException: 9

	at com.avaje.ebean.bean.EntityBeanIntercept.isLoadedProperty(EntityBeanIntercept.java:495)
	at com.avaje.ebean.bean.EntityBeanIntercept.isLazyLoadFailure(EntityBeanIntercept.java:356)
	at com.avaje.ebeaninternal.api.LoadBeanRequest.postLoad(LoadBeanRequest.java:162)
	at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:219)
	at com.avaje.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:501)
	at com.avaje.ebeaninternal.server.loadcontext.DLoadBeanContext$LoadBuffer.loadBean(DLoadBeanContext.java:194)
	at com.avaje.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:774)
	at com.avaje.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:747)
	at com.avaje.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:834)
	at com.avaje.tests.model.basic.Car._ebean_get_notes(Car.java:6)
	at com.avaje.tests.model.basic.Car.getNotes(Car.java:39)
	at com.avaje.tests.inheritance.TestInheritanceBatchLazyLoad.lazyLoadProperty_when_propertyNotOnAllInheritanceTypes(TestInheritanceBatchLazyLoad.java:39)

**Comment by dastultz** [comment]
Yes, Block is an `@Inheritance` class.

Thanks.

**Comment by rbygrave** [comment]
Note: Ultimate issue was in LoadBeanRequest.postLoad() logic. Fixed to just check ids

**Comment by dastultz** [comment]
Fix confirmed, thanks!
