### ISSUE TITLE
Q: Ebean.json().toBean(... json content...) does not make Bean loaded?

### ISSUE THREAD

**Issue by jsh0** [ebean-orm/avaje-ebeanorm#567]
I don't know if this is a bug or if I'm doing something wrong. I want to alter an existing Bean by editing its JSON String. In this case "existing" means, that there is a Bean with same ID which I want to update.

A scenario where this is useful is network communication: A client gets a Bean from server as JSON, alters it and sends it back to server. Then the server uses `Ebean.json().toBean()`.

This is a quick example without sending the JSON over network and without modifying is, as this already yields the unwanted behavior:
```
import java.io.File;
import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.Id;

import com.avaje.ebean.Ebean;
import com.avaje.ebean.EbeanServerFactory;
import com.avaje.ebean.Transaction;
import com.avaje.ebean.config.DataSourceConfig;
import com.avaje.ebean.config.ServerConfig;

@Entity
public class TestSave {
	
	@Id
	private UUID id;
	
    public static void main(String[] args) {
    	// setup
        String databaseName = "test";

        DataSourceConfig ds = new DataSourceConfig();
        ds.setUsername("sa");
        ds.setPassword("");
        ds.setUrl("jdbc:h2:./data/" + databaseName + ";DB_CLOSE_DELAY=-1");
        ds.setDriver("org.h2.Driver");
        ds.setMinConnections(1);
        ds.setMaxConnections(25);
        ds.setHeartbeatSql("select 1");
        ds.setIsolationLevel(Transaction.READ_COMMITTED);

        ServerConfig config = new ServerConfig();
        config.setName(databaseName);
        config.setDataSourceConfig(ds);
        config.setDefaultServer(true);

        config.setDdlGenerate(true);
        config.setDdlRun(!new File("./data/" + databaseName + ".mv.db").exists());

        EbeanServerFactory.create(config);
        
        // test case
        TestSave testSave = new TestSave();
        Ebean.save(testSave);
        
        TestSave fromSomewhereElse = Ebean.json().toBean(TestSave.class, Ebean.json().toJson(testSave));
        Ebean.save(fromSomewhereElse);
    }
	
}
```

By running the `main()`-Method an Exception is thrown:
```
Exception in thread "main" javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[Eindeutiger Index oder Primärschlüssel verletzt: "PRIMARY_KEY_6 ON PUBLIC.TEST_SAVE(ID) VALUES ('3c0d03e0-87a4-46a7-8459-669ff69a8bb2', 1)"\n Unique index or primary key violation: "PRIMARY_KEY_6 ON PUBLIC.TEST_SAVE(ID) VALUES ('3c0d03e0-87a4-46a7-8459-669ff69a8bb2', 1)"; SQL statement:\n insert into test_save (id) values (?) [23505-187]]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:83)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:50)
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:54)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:457)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:491)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:327)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:277)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:265)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1520)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1513)
	at com.avaje.ebean.Ebean.save(Ebean.java:549)
	at model.TestSave.main(TestSave.java:50)
Caused by: org.h2.jdbc.JdbcSQLException: Eindeutiger Index oder Primärschlüssel verletzt: "PRIMARY_KEY_6 ON PUBLIC.TEST_SAVE(ID) VALUES ('3c0d03e0-87a4-46a7-8459-669ff69a8bb2', 1)"
Unique index or primary key violation: "PRIMARY_KEY_6 ON PUBLIC.TEST_SAVE(ID) VALUES ('3c0d03e0-87a4-46a7-8459-669ff69a8bb2', 1)"; SQL statement:
insert into test_save (id) values (?) [23505-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:102)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:233)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:191)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:638)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:146)
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:52)
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:129)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:73)
	... 11 more
```
I would expect that the existing Bean is updated in Database. When using `Ebean.update()` it is working. Debugging `Ebean.save()` shows, that the intercept says, the Entity is not loaded. Is this behavior wanted?

If it is wanted, what is the best practice with Ebean to deal with this? What comes to my mind is checking if the ID already exist in the database and depending on that call `Ebean.insert()` or `Ebean.update()`.

**Comment by rbygrave** [comment]
> Is this behavior wanted?

Yes it is.

> If it is wanted, what is the best practice with Ebean to deal with this?

Use update(). As an further explanation, this 'feature' is what I call "Stateless update" which means being able to perform an update without a prior fetch from the DB. In 4.x we were able to merge the "Stateless update" feature in with the normal updates 


> What comes to my mind is checking if the ID already exist in the database and depending on that call Ebean.insert() or Ebean.update().

The obvious downside there is now EVERY save() requires a query against the DB first to perform that check. That is definitely something we should not get Ebean to do due to cost.  That is more closely aligned to UPSERT or MERGE type statements and there are complications there for DB's.

If you have a REST like service and want to perform an update ... then that is exactly what the "Stateless update" feature is for and it is simply a matter of using update() and not save().  

Does that make sense?

**Comment by rbygrave** [comment]
I'll close this issue. Re-open if needed.

**Comment by jsh0** [comment]
Thanks, you answered my question with this.

I indeed want to perform an update at a REST like service using PUT. But as the client creates the Bean and sends it to the server (with ID), it can be both, an insert or update. Moreover the client can never be sure if the server knows about the Bean without asking the server. So I think, I have to go with the extra query.

**Comment by jsh0** [comment]
I have another question on this issue. There is an object sent as JSON over network and I want to save it. In this object there is another object included twice, so what I would expect is that this object is saved one time and then Ebean notices the object on the second time and does not save it again.

Unfortunately the same Exception as shown above is thrown. I modified the example a bit to represent a twice contained object in a list. My actual example is a bit larger, but I think you get the idea.

```
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import com.avaje.ebean.Ebean;
import com.avaje.ebean.EbeanServerFactory;
import com.avaje.ebean.Transaction;
import com.avaje.ebean.config.DataSourceConfig;
import com.avaje.ebean.config.ServerConfig;

@Entity
public class TestSave {

    @Id
    private UUID id;
    
    @OneToMany(cascade=CascadeType.PERSIST)
    private List<TestSave> otherTestSaves;
    
    @ManyToOne
    private TestSave parent;

    public TestSave(UUID id) {
    	this.id = id;
    	otherTestSaves = new ArrayList<>();
    }
    
    public void addOtherTestSave(TestSave testSave) {
    	otherTestSaves.add(testSave);
    	testSave.parent = this;
    }
    
    public static void main(String[] args) {
        // setup
        String databaseName = "test";

        DataSourceConfig ds = new DataSourceConfig();
        ds.setUsername("sa");
        ds.setPassword("");
        ds.setUrl("jdbc:h2:./data/" + databaseName + ";DB_CLOSE_DELAY=-1");
        ds.setDriver("org.h2.Driver");
        ds.setMinConnections(1);
        ds.setMaxConnections(25);
        ds.setHeartbeatSql("select 1");
        ds.setIsolationLevel(Transaction.READ_COMMITTED);

        ServerConfig config = new ServerConfig();
        config.setName(databaseName);
        config.setDataSourceConfig(ds);
        config.setDefaultServer(true);

        config.setDdlGenerate(true);
        config.setDdlRun(!new File("./data/" + databaseName + ".mv.db").exists());

        EbeanServerFactory.create(config);

        // test case
        UUID id1 = UUID.randomUUID();
        UUID id2 = UUID.randomUUID();
        
        TestSave testSave = new TestSave(id1);
        testSave.addOtherTestSave(new TestSave(id2));
        testSave.addOtherTestSave(new TestSave(id2));
        
        String json = Ebean.json().toJson(testSave);
        System.out.println(json);
        
        TestSave fromSomewhereElse = Ebean.json().toBean(TestSave.class, json);
        Ebean.save(fromSomewhereElse);
    }

}
```

My question is again if this is the wanted behavior. Also, I am not sure how to deal with this problem. Is there another way instead of "manually doing the persist cascade" to check if there is an existing object and not inserting it then?

I see it perfectly makes sense that checking on each object is expensive, but maybe it would be useful to have it in Ebean as option to avoid duplication of code.

**Comment by rbygrave** [comment]
> My question is again if this is the wanted behavior

No it isn't really.  I have logged as https://github.com/ebean-orm/avaje-ebeanorm/issues/577
