### ISSUE TITLE
Using Ebean with SpringLoaded on Spring Boot

### ISSUE THREAD

**Issue by seraphmate** [ebean-orm/avaje-ebeanorm#569]
Hi. I develop some web application using Ebean based on Spring Boot.
I want to use SpringLoaded for hot swap.
After set to use SpringLoaded, my application is not working properly.
This is partial log on tomcat.

`2016-02-18 09:06:11,013 - [main] [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager Error in deployment
javax.persistence.PersistenceException: java.lang.NullPointerException
	at com.avaje.ebeaninternal.server.deploy.parse.DeployCreateProperties.createProperties(DeployCreateProperties.java:138) ~[avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebeaninternal.server.deploy.parse.DeployCreateProperties.createProperties(DeployCreateProperties.java:55) ~[avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createDeployBeanInfo(BeanDescriptorManager.java:1058) ~[avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createEmbedded(BeanDescriptorManager.java:508) ~[avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEmbeddedDeployment(BeanDescriptorManager.java:529) ~[avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:292) ~[avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:129) [avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:124) [avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:41) [avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108) [avaje-ebeanorm-6.12.3.jar:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67) [avaje-ebeanorm-6.12.3.jar:na]
	at kr.co.xmd.service.EbeanFactoryBean.getObject(EbeanFactoryBean.java:42) [main/:na]
	at kr.co.xmd.service.EbeanFactoryBean.getObject(EbeanFactoryBean.java:17) [main/:na]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]`

I'm using spring boot 1.3.0, springloaded 1.2.5.
My Ebean libraries setting on build.gradle is
`compile('org.avaje.ebeanorm:avaje-ebeanorm:6.12.3')
compile('org.avaje.ebeanorm:avaje-ebeanorm-agent:4.7.1')
compile('org.avaje:avaje-agentloader:2.1.2')`

If there is someone using Ebean with SpringLoaded, give me some advice.
Sorry for my messy question, Thanks.

**Comment by rbygrave** [comment]
Note that you reach a limited audience logging this as a issue and instead you could try posting to the google group:

https://groups.google.com/forum/#!forum/ebean

**Comment by rbygrave** [comment]
I'll close this issue for now.  Re-open or try the google group etc. Thanks, Rob.

**Comment by root-talis** [comment]
Please post a link to the google group ticket next time.
