### ISSUE TITLE
Cast exception on initialized collection

### ISSUE THREAD

**Issue by dastultz** [ebean-orm/avaje-ebeanorm#591]
Hi Rob, we unleashed Ebean 6 into the wild last week, here's the first of a couple problems.

Given an entity with a field declared as:

```
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "timeTrackingEntry") 
private List<CustomProperty> customProperties = new ArrayList<CustomProperty>(0); 
```

We get this exception:

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.avaje.ebean.bean.BeanCollection
        at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.addBeanToCollectionWithCreate(BeanPropertyAssocMany.java:186)
        at com.avaje.ebeaninternal.server.query.SqlTreeNodeManyRoot.load(SqlTreeNodeManyRoot.java:27)
        at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:296)
        at com.avaje.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:437)
        at com.avaje.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:512)
        at com.avaje.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:543)
        at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:302)
        at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:94)
        at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:296)
        at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1449)
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1062)
     
```

We consider it a "mistake" on the developer's part to initialize a collection - we generally want the BeanSet, BeanList, etc. Just the same it seems like a bug that it crashes trying to cast it.

We've removed the initialization so we are not dependent on this being fixed.

**Comment by rbygrave** [comment]
What version of the Ebean agent are you using?

That is, the enhancement detects this case and removes that new
ArrayList<CustomProperty>(0); call.
This came in with agent version 4.5.4 Issue #16 -
https://github.com/ebean-orm/avaje-ebeanorm-agent/issues/16

**Comment by dastultz** [comment]
Sorry, Ebean 6.16.3, enhancement agent 4.1.4. I guess that explains it.
