### ISSUE TITLE
Fetched empty collection of null child of parent entity

### ISSUE THREAD

**Issue by dastultz** [ebean-orm/avaje-ebeanorm#592]
Given an entity A with a child of B with a collection of C, if one queries A and fetches b.c, and b is null we get the following crash. Note the fetch part. We ran into this problem on production where the auto tuner added the fetch for c. Naturally our real model is slightly more complex so there may be something else going on (complementary pointers between A and B).

If we explicitly add a new FetchConfig().query() (or lazy()) we can work around the problem. (Now we're a bit concerned about a "ticking time bomb" in other parts of our application...)

```
java.lang.RuntimeException: get c on [B] type[null] threw error.
        at com.avaje.ebeaninternal.server.deploy.BeanProperty.getValue(BeanProperty.java:728)
        at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.addBeanToCollectionWithCreate(BeanPropertyAssocMany.java:186)
        at com.avaje.ebeaninternal.server.query.SqlTreeNodeManyRoot.load(SqlTreeNodeManyRoot.java:27)
        at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:296)
        at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:296)
        at com.avaje.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:437)
        at com.avaje.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:512)
        at com.avaje.ebeaninternal.server.query.CQuery.readCollection(CQuery.java:543)
        at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:302)
        at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:94)
        at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findSet(OrmQueryRequest.java:308)
        at com.avaje.ebeaninternal.server.core.DefaultServer.findSet(DefaultServer.java:1242)
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findSet(DefaultOrmQuery.java:1066)
 ```

**Comment by rbygrave** [comment]
*>  A with a child of B*

Can you detail the relationships - state the relationship annotations used
such as @ManyToOne(...), @OneToOne(...) etc?

**Comment by rbygrave** [comment]
It could also be this is related to using an old version of the enhancement
agent.

**Comment by dastultz** [comment]
I've spent the last bit trying to update the enhancer version. I can't get anything after 4.1.4 of the enhancer to work for me. The issues seem to be around @MappedSuperclass and @Id. I get one of these depending on how I launch my test(s):

`java.lang.NoSuchFieldError: _ebean_intercept`
or
`java.lang.AbstractMethodError: x.y.z.Thing._ebean_getIntercept()Lcom/avaje/ebean/bean/EntityBeanIntercept;`

I have a `PersistentEntity` class that is the @MappedSuperclass of all my entities (with some intermediate subclasses here and there).

I'd like to rule out enhancement on this issue first. I guess I'll open an issue on the agent project.

**Comment by rbygrave** [comment]
The new version of the agent will fix that NoSuchFieldError ... so I think I am waiting to see if this issue is still a problem.

**Comment by dastultz** [comment]
Enhancement issue has been resolved. Original failure still present. I started to create an isolated test case, but the runtime behavior of the enhancer doesn't seem to be working. Is there any way you can create a skeleton Maven project for creating test cases (and post the repo on GitHub)? This would be quite useable for everyone that comes along with an issue.

I have a `TimeCardSwipeEvent` with 

```
@OneToOne(mappedBy = "outTimeCardSwipeEvent")
	private TimeTrackingEntry outTimeTrackingEntry;
```

`TimeTrackingEntry` has

```
@OneToMany(cascade = CascadeType.ALL, mappedBy = "timeTrackingEntry")
	private List<RoleTimeCredit> roleTimeCredits;
```

The query is

```
		Query<TimeCardSwipeEvent> query = ExecutionResources.getEbeanServer().find(TimeCardSwipeEvent.class)
				.fetch("outTimeTrackingEntry.roleTimeCredits")
				.where()
				.eq(TimeCardSwipeEvent.pId, 1234)
				.query();
```

So `outTimeTrackingEntry` is null in this case. If I change `roleTimeCredits` to `scheduledAssignment` which is a single relation instead of a collection, it works fine.

**Comment by rbygrave** [comment]
There exists:
https://github.com/ebean-orm/example-java8 ... which probably the most
minimal.

There are also the ones in:
https://github.com/ebean-orm/avaje-ebeanorm-examples

... I'll re-org the example projects though.  Too hard to find at the
moment.

**Comment by dastultz** [comment]
Fix confirmed, thanks.
