### ISSUE TITLE
NullPointerException - while accessing empty @DbJsonB(JsonNode) object - trying to lazy loading!

### ISSUE THREAD

**Issue by rchincho** [ebean-orm/avaje-ebeanorm#598]
2016-03-14 00:55:01,614 - [DEBUG] - org.avaje.ebean.TXN - txn[1005] Commit
2016-03-14 00:55:01,667 - [ERROR] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.NullPointerException: null
	at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:379) ~[avaje-ebeanorm-6.8.1.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:392) ~[avaje-ebeanorm-6.8.1.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:374) ~[avaje-ebeanorm-6.8.1.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:512) ~[avaje-ebeanorm-6.8.1.jar:na]
	at com.avaje.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:751) ~[avaje-ebeanorm-6.8.1.jar:na]
	at com.avaje.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:716) ~[avaje-ebeanorm-6.8.1.jar:na]
	at com.avaje.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:811) ~[avaje-ebeanorm-6.8.1.jar:na]
	at com.htr.desque.models.EstimateJsonData._ebean_get_calculation(EstimateJsonData.java:6) ~[classes/:na]
	at com.htr.desque.models.EstimateJsonData.getCalculation(EstimateJsonData.java:36) ~[classes/:na]
	at com.htr.desque.models.EstimateJsonData.writeObject(EstimateJsonData.java:52) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988) ~[na:1.8.0_51]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.8.0_51]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_51]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_51]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_51]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_51]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_51]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_51]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_51]
	at com.github.mumoshu.play2.memcached.CustomSerializing.serialize(CustomSerializing.scala:24) ~[play2-memcached-play24_2.11-0.7.0.jar:0.7.0]
	at net.spy.memcached.transcoders.SerializingTranscoder.encode(SerializingTranscoder.java:162) ~[spymemcached-2.9.0.jar:2.9.0]
	at net.spy.memcached.MemcachedClient.asyncStore(MemcachedClient.java:291) ~[spymemcached-2.9.0.jar:2.9.0]
	at net.spy.memcached.MemcachedClient.set(MemcachedClient.java:807) ~[spymemcached-2.9.0.jar:2.9.0]

**Comment by rbygrave** [comment]
Are you creating a reproducing test case?

**Comment by rbygrave** [comment]
Also note that for me personally I believe it is not good practice to cross-post a single issue to multiple projects without stating that you are doing that.  The implication is that you do not care that you might be wasting people's time.

I'm taking about: 
https://github.com/playframework/play-ebean/issues/79

**Comment by rchincho** [comment]
@rbygrave Sorry inconvenience caused.

I'm trying serialize JsonB object to store in Memcached. It works fine with non null DB object columns.

**Comment by rbygrave** [comment]
Are you producing test case?

**Comment by rbygrave** [comment]
Are you producing a test case?

**Comment by rbygrave** [comment]
@rchincho ... you are not responding so I'll close this issue.  I would expect a test case, if you prepare one or have further details you can add a comment or reopen. Thanks.
