### ISSUE TITLE
NotifyOfCommit failed. L2 Cache potentially not notified.

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#603]
```java
13:04:00.441 [BspQuartzScheduler_Worker-4] ERROR c.a.e.s.t.TransactionManager - NotifyOfCommit failed. L2 Cache potentially not notified.
java.util.concurrent.RejectedExecutionException: Task com.avaje.ebeaninternal.server.transaction.PostCommitProcessing$1@44a552d1 rejected from com.avaje.ebeaninternal.server.lib.DaemonThreadPool@1c52372b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 7119]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048) ~[na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821) ~[na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372) ~[na:1.7.0_67]
        at com.avaje.ebeaninternal.server.core.DefaultBackgroundExecutor.execute(DefaultBackgroundExecutor.java:40) ~[avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebeaninternal.server.transaction.TransactionManager.notifyOfCommit(TransactionManager.java:400) ~[avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.notifyCommit(JdbcTransaction.java:800) [avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebeaninternal.server.transaction.JdbcTransaction.commit(JdbcTransaction.java:882) [avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebeaninternal.server.core.BeanRequest.commitTransIfRequired(BeanRequest.java:56) [avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:370) [avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:347) [avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1506) [avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1499) [avaje-ebeanorm-6.18.1.jar:na]
        at com.avaje.ebean.Ebean.update(Ebean.java:628) [avaje-ebeanorm-6.18.1.jar:na]
        at com.sinitek.fiabsp.resources.core.PushService.handlePushList(PushService.java:94) [fia-bsp-1.0.0.jar:na]
        at com.sinitek.fiabsp.app.jobs.RoadShowPushJob.execute(RoadShowPushJob.java:69) [fia-bsp-1.0.0.jar:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [quartz-1.8.6.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [quartz-1.8.6.jar:na]
```

**Comment by rbygrave** [comment]
You need to actually write some text to explain if you are asking a question or think you have an issue or something.  Simply posting a stack trace is not sufficient.

Thanks, Rob.

**Comment by rbygrave** [comment]
I'm awaiting some actual comment / question / statement for this issue.  I'll close it and if there is a comment / question then you can add it and perhaps re-open the issue. Thanks.
