### ISSUE TITLE
@SoftDelete with deletePermanent() on lazy loaded @OneToOne gives NPE

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/avaje-ebeanorm#604]
Hi,

When @SoftDelete is used, Ebean trigger `boolean delete()` method of all Model objects linked to soft deleted object. But nothing exist when deletePermanent() is processed.

By exemple, we have a S3File model who handle link to Amazon S3 file. We want that the s3 file was deleted during a hard delete but not when we use a soft delete.

In the same way, with a OneToOne  A -- B, when A is soft delete, B too, but a.b_id is set to NULL, so when we "undelete" A, B is no longer linked to A.

**Comment by rbygrave** [comment]
Hi,

I would help me if you could provide a test case that showed me the scenario.  It looks like 'S3File model ' is an entity bean that is related to another entity bean which we are using soft delete with.

If you can post up the entity bean models and / or provide a test case that helps me know exactly what the scenario is.

Thanks, Rob.

**Comment by 0xbaadf00d** [comment]
Hi,

With a new clean project, SoftDelete seems working, but; we got a new issue concerning the Lazy fetch functionnality. Soft delete is OK, but hard delete generate a NullPointerException.

app/models/Album.java (line 26) : If `fetch = FetchType.LAZY` is enabled, we got a NullPointerException during the deletion process.

https://dl.dropboxusercontent.com/u/37895949/github.com/demo-play-soft-delete.zip

## Output 

##### Application start
	[info] - application - apply - Creating Pool for datasource 'default'
	[info] - play.api.db.DefaultDBApi - apply - Database [default] connected at jdbc:h2:mem:play
	[info] - play.api.Play - start - Application started (Dev)


##### GET /seed
	[debug] - org.avaje.ebean.SQL - logSql - txn[1001] select t0.id c0, t0.created_at c1, t0.last_update c2, t0.name c3, t0.deleted c4 from album t0
	[debug] - org.avaje.ebean.SQL - logSql - txn[1002] select t0.id c0, t0.s3url c1, t0.deleted c2 from cover t0
	[debug] - org.avaje.ebean.SQL - logSql - txn[1003] insert into cover (id, s3url, deleted) values (?,?,?)
	[debug] - org.avaje.ebean.SQL - logSql - txn[1004] insert into album (id, created_at, last_update, name, deleted, cover_id) values (?,?,?,?,?,?)


##### GET /
	[debug] - org.avaje.ebean.SQL - logSql - txn[1005] select t0.id c0, t0.created_at c1, t0.last_update c2, t0.name c3, t0.deleted c4 from album t0
	[debug] - org.avaje.ebean.SQL - logSql - txn[1006] select t0.id c0, t0.created_at c1, t0.last_update c2, t0.name c3, t0.deleted c4, t0.cover_id c5 from album t0 where t0.id = ?
	[debug] - org.avaje.ebean.SQL - logSql - txn[1007] select t0.id c0, t0.s3url c1, t0.deleted c2 from cover t0 where t0.id = ?


##### GET /soft-delete
	[debug] - org.avaje.ebean.SQL - logSql - txn[1008] select t0.id c0, t0.created_at c1, t0.last_update c2, t0.name c3, t0.deleted c4 from album t0 where coalesce(t0.deleted,false)=false
	[debug] - org.avaje.ebean.SQL - logSql - txn[1009] select t0.id c0, t0.cover_id c1 from album t0 where t0.id = ?  and coalesce(t0.deleted,false)=false
	[debug] - org.avaje.ebean.SQL - logSql - txn[1009] update album set last_update=?, deleted=? where id=?
	[debug] - org.avaje.ebean.SQL - logSql - txn[1009] update cover set deleted=? where id=?


##### GET /hard-delete
	[debug] - org.avaje.ebean.SQL - logSql - txn[1014] select t0.id c0, t0.cover_id c1 from album t0 where t0.id = ?  and coalesce(t0.deleted,false)=false
	[debug] - org.avaje.ebean.SQL - logSql - txn[1014] delete from album where id=?
	[error] - application - logServerError -

	! @6pei2pgl9 - Internal server error, for (GET) [/hard-delete] ->

	play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: get cover on [models.Album] type[null] threw error.]]
			at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.6.jar:2.4.6]
			at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.6.jar:2.4.6]
			at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.6.jar:2.4.6]
			at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [play-netty-server_2.11-2.4.6.jar:2.4.6]
			at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [play-netty-server_2.11-2.4.6.jar:2.4.6]
			at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
			at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
			at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
			at scala.util.Failure.recover(Try.scala:216) [scala-library-2.11.7.jar:na]
			at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
			at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
			at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
			at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.6.jar:2.4.6]
			at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.6.jar:2.4.6]
			at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
			at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
			at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
			at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
			at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.7.jar:na]
			at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
			at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
			at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
			at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
			at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
			at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
	Caused by: java.lang.RuntimeException: get cover on [models.Album] type[null] threw error.
			at com.avaje.ebeaninternal.server.deploy.BeanProperty.getValue(BeanProperty.java:728) ~[avaje-ebeanorm-6.14.1.jar:na]
			at com.avaje.ebeaninternal.server.persist.DeleteUnloadedForeignKeys.deleteCascade(DeleteUnloadedForeignKeys.java:87) ~[avaje-ebeanorm-6.14.1.jar:na]
			at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:768) ~[avaje-ebeanorm-6.14.1.jar:na]
			at com.avaje.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:542) ~[avaje-ebeanorm-6.14.1.jar:na]
			at com.avaje.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:522) ~[avaje-ebeanorm-6.14.1.jar:na]
			at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:514) ~[avaje-ebeanorm-6.14.1.jar:na]
			at com.avaje.ebeaninternal.server.core.DefaultServer.deletePermanent(DefaultServer.java:1908) ~[avaje-ebeanorm-6.14.1.jar:na]
			at com.avaje.ebeaninternal.server.core.DefaultServer.deletePermanent(DefaultServer.java:1903) ~[avaje-ebeanorm-6.14.1.jar:na]
			at models.BaseModel.deletePermanent(BaseModel.java:116) ~[classes/:2.4.6]
			at controllers.HomeController.GET_HardDelete(HomeController.java:58) ~[classes/:2.4.6]
			at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(Routes.scala:173) ~[classes/:na]
			at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(Routes.scala:173) ~[classes/:na]
			at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[play_2.11-2.4.6.jar:2.4.6]
			at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.7.jar:na]
			at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.7.jar:na]
			at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) [play-iteratees_2.11-2.4.6.jar:2.4.6]
			at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[play_2.11-2.4.6.jar:2.4.6]
			at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[scala-library-2.11.7.jar:na]
			at scala.concurrent.Future$.apply(Future.scala:492) ~[scala-library-2.11.7.jar:na]
			at play.core.j.JavaAction.apply(JavaAction.scala:94) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.11-2.4.6.jar:2.4.6]
			at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
			at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.11-2.4.6.jar:2.4.6]
			at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
			at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
			at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
			at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
			at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
			at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) ~[play-iteratees_2.11-2.4.6.jar:2.4.6]
			at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.7.jar:na]
			at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.7.jar:na]
			... 6 common frames omitted
	Caused by: java.lang.NullPointerException: null
			at com.avaje.ebeaninternal.server.properties.EnhanceBeanPropertyInfo$Getter.get(EnhanceBeanPropertyInfo.java:67) ~[avaje-ebeanorm-6.14.1.jar:na]
			at com.avaje.ebeaninternal.server.deploy.BeanProperty.getValue(BeanProperty.java:724) ~[avaje-ebeanorm-6.14.1.jar:na]
			... 47 common frames omitted

**Comment by rbygrave** [comment]
FYI
I have logged the issue with findRowCount() separately as #611 and this is now fixed in master.

**Comment by rbygrave** [comment]
The required sql and summary logging for this deletePermanent() case with lazy OneToOne is:

```sql
SUM - txn[1008] -- Ebean fetching foreign key values for delete of Album id:1
SQL - txn[1008] select t0.id c0, t0.cover_id c1 from album t0 where t0.id = ?  ; --bind(1)
SUM - txn[1008] FindBean type[Album] origin[BXUR3z.jre1M.WMipP] exeMicros[263] rows[1] bind[1]
SQL - txn[1008] delete from album where id=?; --bind(1,)
SUM - txn[1008] Deleted [Album] [1]
SQL - txn[1008] delete from cover where id=?; --bind(1,)
SUM - txn[1008] Deleted [Cover] [1]
```
