### ISSUE TITLE
ElasticSearch expression - IllegalArgumentException: unhandled type class org.example.domain.Customer

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#616]
So when we use 'reference' beans in the expression language like Customer below the expectation is that Ebean detects this and uses the matching 'Id' property.

In the case below we expected customer.id to be used.

```java

    Customer custOne = Ebean.getReference(Customer.class, 1);

    Query<Order> query = Ebean.find(Order.class)
        .where().eq("customer", custOne)
        .query();
```

java.lang.IllegalArgumentException: unhandled type class org.example.domain.Customer

	at com.avaje.ebeaninternal.server.text.json.DJsonScalar.write(DJsonScalar.java:29)
	at com.avaje.ebeaninternal.server.text.json.DJsonContext.writeScalar(DJsonContext.java:66)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticJsonContext.writeScalar(ElasticJsonContext.java:51)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.writeRawExpression(ElasticDocQueryContext.java:634)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.writeEqualTo(ElasticDocQueryContext.java:402)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.writeSimple(ElasticDocQueryContext.java:649)
	at com.avaje.ebeaninternal.server.expression.SimpleExpression.writeDocQuery(SimpleExpression.java:38)
	at com.avaje.ebeaninternal.server.expression.DefaultExpressionList.writeDocQuery(DefaultExpressionList.java:141)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.writeFilter(ElasticDocQueryContext.java:135)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.writeElastic(ElasticDocQueryContext.java:113)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.asElasticQuery(ElasticDocQueryContext.java:92)
	at com.avaje.ebeanservice.elastic.querywriter.ElasticDocQueryContext.asJson(ElasticDocQueryContext.java:69)
	at com.avaje.ebeaninternal.server.expression.BaseElasticTest.asJson(BaseElasticTest.java:18)
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQueryElasticTest.simpleExpression_on_assocId(DefaultOrmQueryElasticTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)

**Comment by rbygrave** [comment]
The expected Elastic query is:

```json
"{"query":{"filtered":{"filter":{"term":{"customer.id":1}}}}}"
```
