### ISSUE TITLE
EbeanServer.shutdown(true, false) followed by EbeanServerFactory create() when using the same ServerConfig give SQLException: Trying to access the Connection Pool when it is shutting down

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#621]
So if I do:

```java
ServerConfig config = new ServerConfig();
config.setName("h2");
...
EbeanServer ebeanServer = EbeanServerFactory.create(config);

ebeanServer.shutdown(true, false); // shutdown DataSource = true

// create anther instance
EbeanServer anotherServer = EbeanServerFactory.create(config);

```
I get a different stack trace.  I get:

    javax.persistence.PersistenceException: java.sql.SQLException: Trying to access the Connection Pool when it is shutting down

	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:361)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:102)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:41)
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
	at com.avaje.ebean.EbeanServerFactory_ServerConfigStart_Test.test(EbeanServerFactory_ServerConfigStart_Test.java:43)
	...
    Caused by: java.sql.SQLException: Trying to access the Connection Pool when it is shutting down
	at org.avaje.datasource.pool.PooledConnectionQueue._getPooledConnection(PooledConnectionQueue.java:297)
	at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:271)
	at org.avaje.datasource.pool.ConnectionPool.getPooledConnection(ConnectionPool.java:712)
	at org.avaje.datasource.pool.ConnectionPool.getConnection(ConnectionPool.java:700)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:351)
	... 40 more

**Comment by rbygrave** [comment]
If you don't shutdown the datasource then the error does not occur.

```java
// do not shutdown the datasource
ebeanServer.shutdown(false, false);
```

... and that is fine because the DataSource from the first EbeanServer instance is left running.

Alternatively if I set DataSource to null on ServerConfig like:

```java
// shutdown the datasource
ebeanServer.shutdown(true, false);

// set datasource to null on ServerConfig forcing Ebean to create a new DataSource
config.setDataSource(null);
```

... so this is also fine.

**Comment by rbygrave** [comment]
Right now I believe that the "fix" for this is that when you shutdown an EbeanServer instance AND datasource shutdown is TRUE ... then Ebean should implicitly set the DataSource to null on the ServerConfig.

That would fix this issue and also allow people to re-user a DataSource between "a EbeanServer restart".
