### ISSUE TITLE
NPE on OrmQueryProperties.java:474

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#643]
java.lang.NullPointerException: null 
    at com.avaje.ebeaninternal.server.querydefn.OrmQueryProperties.isSameByAutoTune(OrmQueryProperties.java:474) 
    at com.avaje.ebeaninternal.server.querydefn.OrmQueryDetail.isSameByAutoTune(OrmQueryDetail.java:133) 
    at com.avaje.ebeaninternal.server.querydefn.OrmQueryDetail.isAutoTuneEqual(OrmQueryDetail.java:124) 
    at com.avaje.ebeaninternal.server.autotune.service.AutoTuneDiffCollection.addToDocument(AutoTuneDiffCollection.java:105) 
    at com.avaje.ebeaninternal.server.autotune.service.AutoTuneDiffCollection.process(AutoTuneDiffCollection.java:88)
    at com.avaje.ebeaninternal.server.autotune.service.DefaultAutoTuneService.runtimeTuningUpdate(DefaultAutoTuneService.java:129) 
    at com.avaje.ebeaninternal.server.autotune.service.DefaultAutoTuneService.access$100(DefaultAutoTuneService.java:20) 
    at com.avaje.ebeaninternal.server.autotune.service.DefaultAutoTuneService$ProfilingUpdate.run(DefaultAutoTuneService.java:95)

**Comment by rbygrave** [comment]
I think changing it to something like this would solve the problem and still make good semantic sense (but it could also be solved in OrmQueryDetail).

```java
/**
 * Return true if the properties are the same for autoTune purposes.
 */
public boolean isSameByAutoTune(OrmQueryProperties p2) {
   if (included == null) {
      return p2 == null || p2.included == null;
   } else if (p2 == null) {
      return false;
   }
   return included.equals(p2.included);
}
```
Thanks,

/Daryl (and Steven)

**Comment by rbygrave** [comment]
Reproduces with:

```java

  @Test
  public void isAutoTuneEqual_when_different_path() {

    OrmQueryDetail detail1 = parse("select (id,name) fetch customer (name)");
    OrmQueryDetail detail2 = parse("select (id,name) fetch details (id) ");

    assertFalse(detail1.isAutoTuneEqual(detail2));
    assertFalse(detail2.isAutoTuneEqual(detail1));
  }

```
