### ISSUE TITLE
ENH: Add ability to register a custom IdGenerator

### ISSUE THREAD

**Issue by xxcode-monkey** [ebean-orm/avaje-ebeanorm#668]
There have `UuidIdGenerator` for `UUID` type id field out of box in Ebean , But sometimes for `String` type id field `UuidIdGenerator` helps . So can add ability to register customize IdGenerator .
maybe add a configration like `EncryptKeyManager` in `ServerConfig`

**Comment by rbygrave** [comment]
There is now a new interface that custom Id generators can implement:

```java
package com.avaje.ebean.config;

/**
 * A customer Id generator that can be registered with Ebean and
 * assigned to @Id properties using the name attribute of @GeneratedValue.
 */
public interface IdGenerator {

  /**
   * Return the next Id value.
   */
  Object nextValue();

  /**
   * Return the name of the IdGenerator.
   * <p>
   * The name is used to assign the IdGenerator to a property using
   * <code>@GeneratedValue(name="myGeneratorName")</code>
   * </p>
   */
  String getName();
}
```

An example is:
```java
package org.example;

import com.avaje.ebean.config.IdGenerator;
import org.avaje.moduuid.ModUUID;

/**
 * A customer Id Generator that can be assigned by @GeneratedValue(generator="shortUid")
 */
public class ModUuidGenerator implements IdGenerator {

  @Override
  public Object nextValue() {
    return ModUUID.newShortId();
  }

  @Override
  public String getName() {
    return "shortUid";
  }
}
```

This will automatically be picked up with classpath scanning (like entity beans and other things) but can also be explicitly registered with ServerConfig via addClass() ... or via new methods.


New methods on ServerConfig:

```java
  /**
   * Return the custom IdGenerator instances.
   */
  public List<IdGenerator> getIdGenerators() {
    return idGenerators;
  }

  /**
   * Set the custom IdGenerator instances.
   */
  public void setIdGenerators(List<IdGenerator> idGenerators) {
    this.idGenerators = idGenerators;
  }

  /**
   * Register a customer IdGenerator instance.
   */
  public void add(IdGenerator idGenerator) {
    idGenerators.add(idGenerator);
  }
```

**Comment by rbygrave** [comment]
To specify the use of the custom Id generator we use @GeneratedValue(name="...") like:

```java
  // where "shortUid" is the name of the Id generator registered
  @Id @GeneratedValue(generator = "shortUid")
  String id;
```

**Comment by KGCybeX** [comment]
To specify the use of the custom Id generator we use @generatedvalue(name="...") like:
```
  // where "shortUid" is the name of the Id generator registered
  @Id @GeneratedValue(generator = "shortUid")
  String id;
```

I did **exactly** this, and am receiving the following error:

`java.lang.IllegalStateException: No custom IdGenerator registered with name shortUid`

**Comment by Tarrowren** [comment]
java.lang.IllegalStateException: No custom IdGenerator registered with name uuid

**Comment by rbygrave** [comment]
Sounds like the customer IdGenerator is not registered?  So how did you register it?

**Comment by Tarrowren** [comment]
```java
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "uuid") // is ok
```
```java
@GeneratedValue(generator = "uuid") // default AUTO, throw err
```
may be it is a bug

**Comment by Tarrowren** [comment]
this is my code:
```java

import io.ebean.Model;
import io.ebean.annotation.Length;
import io.ebean.annotation.NotNull;
import io.ebean.annotation.WhenCreated;
import io.ebean.annotation.WhenModified;
import java.time.Instant;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import lombok.Data;

@Entity
@Data
public class Hello extends Model {

    @Id
    @Length(36)
    @GeneratedValue(generator = "uuid")
    private String id;

    @WhenCreated
    private Instant whenCreated;

    @WhenModified
    private Instant whenModified;

    @NotNull
    @Length(12)
    private String name;
}
```
```java
import io.ebean.config.IdGenerator;
import java.util.UUID;
import org.springframework.stereotype.Component;

@Component
public class UUIDIdGenerator implements IdGenerator {

    @Override
    public String nextValue() {
        return UUID.randomUUID().toString();
    }

    @Override
    public String getName() {
        return "uuid";
    }
}
```

```java
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.giga.workflow.mytest.entities.Hello;
import com.giga.workflow.mytest.utils.UUIDIdGenerator;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class HelloCtrlTest {

    @Autowired
    private UUIDIdGenerator uuid;

    @Test //√
    public void testUUIDBean() {
        assertNotNull(uuid);
    }

    @Test //×
    public void testInsert() {
        var foo = new Hello();
        foo.setName("foo");
        foo.save();

        assertNotNull(foo.getId());
    }
}
```

**Comment by Tarrowren** [comment]
use default db will throw exception
```yaml
// application-test.yaml
ebean:
    test:
        platform: h2
        ddlMode: dropCreate
    db:
        ddl:
            generate: true
            run: true

datasource:
    db:
        username: sa
        password: sa
        url: jdbc:h2:mem:test
        driver: org.h2.Driver

```
```java
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.giga.workflow.mytest.entities.Hello;
import io.ebean.Database;
import io.ebean.DatabaseFactory;
import io.ebean.config.DatabaseConfig;
import io.ebean.datasource.DataSourceConfig;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class HelloCtrlTest {

    private Database database;

    public HelloCtrlTest() {
        var dataSourceConfig = new DataSourceConfig();
        dataSourceConfig.setDriver("org.h2.Driver");
        dataSourceConfig.setUrl("jdbc:h2:mem:my");
        dataSourceConfig.setUsername("sa");
        dataSourceConfig.setPassword("sa");

        var config = new DatabaseConfig();
        config.setDataSourceConfig(dataSourceConfig);

        config.setDatabasePlatformName("h2");

        config.setDefaultServer(false);
        config.setRegister(false);

        config.setDdlGenerate(true);
        config.setDdlRun(true);

        this.database = DatabaseFactory.create(config);
    }

    @Test // No custom IdGenerator registered with name uuid
    public void testInsert() {
        var foo = new Hello();
        foo.setName("foo");
        foo.save();

        assertNotNull(foo.getId());
        System.out.println(foo.getId());
    }

    @Test // ok
    public void testInsert2() {
        var foo = new Hello();
        foo.setName("foo");
        this.database.save(foo);

        assertNotNull(foo.getId());
        assertEquals(36, foo.getId().length());
    }
}
```

**Comment by Tarrowren** [comment]
run migration also throw this exception, I need to comment out @ generatedvalue (generator = UUID) every time run migration
```java
import com.giga.workflow.mytest.utils.UUIDIdGenerator;
import io.ebean.annotation.Platform;
import io.ebean.config.DatabaseConfig;
import io.ebean.dbmigration.DbMigration;
import java.io.IOException;

public class GenerateDbMigration {

    public static void main(String[] args) throws IOException {
        var config = new DatabaseConfig();
        config.add(new UUIDIdGenerator());

        var dbMigration = DbMigration.create();
        dbMigration.setServerConfig(config);
        dbMigration.setStrictMode(false);
        dbMigration.setPlatform(Platform.MYSQL);
        dbMigration.generateMigration();
    }
}
```
```
Caused by: java.lang.IllegalStateException: No custom IdGenerator registered with name uuid
        at io.ebeaninternal.server.deploy.parse.AnnotationFields.readGenValue(AnnotationFields.java:570)
        at io.ebeaninternal.server.deploy.parse.AnnotationFields.initIdentity(AnnotationFields.java:230)
        at io.ebeaninternal.server.deploy.parse.AnnotationFields.readField(AnnotationFields.java:201)
        at io.ebeaninternal.server.deploy.parse.AnnotationFields.parse(AnnotationFields.java:114)
        at io.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:35)
        ... 16 more
```
