### ISSUE TITLE
Trouble with non-standard java.sql.Date values caching in 7.8.1.

### ISSUE THREAD

**Issue by npokr** [ebean-orm/avaje-ebeanorm#686]
## Expected behavior
There is field with type date and default 'infinity'::date (postgres). I want cache rows with such values and this test must pass:
```
    public void testFindByUsername() throws Exception {
        User guest = new User();
        guest.setUsername("guest");
        service.insert(guest);
        
        guest = service.findByUsername("guest");
        assertNotNull(guest);
        guest = service.findByUsername("guest");
        assertNotNull(guest);
    }
```
(User has field private Date expiredAt with infinity server default)

## Actual behavior
```
java.lang.NumberFormatException: For input string: " 994"

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.sql.Date.valueOf(Date.java:133)
	at com.avaje.ebeaninternal.server.type.ScalarTypeBaseDate.parse(ScalarTypeBaseDate.java:59)
	at com.avaje.ebeaninternal.server.type.ScalarTypeWrapper.parse(ScalarTypeWrapper.java:128)
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.setCacheDataValue(BeanProperty.java:770)
	at com.avaje.ebeaninternal.server.cache.CachedBeanDataToBean.loadProperty(CachedBeanDataToBean.java:41)
	at com.avaje.ebeaninternal.server.cache.CachedBeanDataToBean.load(CachedBeanDataToBean.java:25)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.loadBeanDirect(BeanDescriptorCacheHelp.java:493)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.loadBean(BeanDescriptorCacheHelp.java:472)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.beanCacheGetInternal(BeanDescriptorCacheHelp.java:462)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.naturalKeyLookup(BeanDescriptorCacheHelp.java:318)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.cacheNaturalKeyLookup(BeanDescriptor.java:1219)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1121)
```

### Steps to reproduce
Create cacheable entity with date field and try fetch row with "strange" value (i.e. with more-then-4-digit year) from cache.
It is new trouble, 7.6.1 does not restore dates from invalid strings.

**Comment by rbygrave** [comment]
You need to provide more information.  You have not included your entity bean and this stack trace suggests you are using a non-standard type (ScalarTypeWrapper).

It might be easier to create a simple test that creates such a java.sql.Date and uses ScalarTypeDate to format() and parse() the value to reproduce your problem.

**Comment by npokr** [comment]
Test project: https://github.com/npokr/test-ebean-cache
(sorry, test cannot run as gradle task because used plugin exists only in my mavenLocal())
But simple test is very simple:
```
public void testDate() throws Exception {
        Date original = Date.valueOf(LocalDate.of(20000, 1, 1));
        String s = original.toString();
        Date restored = Date.valueOf(s);
    }
```
where Date is java.sql.Date

**Comment by rbygrave** [comment]
So this issue could be summarised as:

ScalarTypeDate can't handle formatting and parsing this date:
```java
Date largeDate = new Date(9223372036825200000L);
```

The test case is effecively:
```java
  ScalarTypeDate type = new ScalarTypeDate();

  @Test
  public void formatParse_PG_DATE_POSITIVE_INFINITY() {

    Date postgresInfinityDate = new Date(9223372036825200000L);

    String format = type.formatValue(postgresInfinityDate);
    Date parsed = type.parse(format);
    assertEquals(parsed, postgresInfinityDate);
  }
```

**Comment by rbygrave** [comment]
To be explicit, yes I reproduced with the test case above and yes it is now fixed in master.
