### ISSUE TITLE
Cannot write tests in simple example – IllegalStateException: Bean class not enhanced

### ISSUE THREAD

**Issue by ncphillips** [ebean-orm/avaje-ebeanorm#756]
## Expected behavior
I am writing a Java sbt module that uses Ebean, but I am having trouble getting a test database setup to run tests. 

## Actual behavior
When trying to get the server, it throws an `IllegalStateException` saying Person is not enhanced.

### Steps to reproduce

*src/test/resources/ebean.properties*

```
ebean.ddl.generate=true
ebean.ddl.run=true
ebean.ddl.createOnly=true
ebean.db=["models.*"]

datasource.default=db

datasource.db.username=sa
datasource.db.password=
datasource.db.databaseUrl=jdbc:h2:mem:tests
datasource.db.databaseDriver=org.h2.Driver
```

*src/test/models/Person.java*
```java
package models;

import javax.persistence.Entity;
import javax.persistence.Id;


@Entity
public class Person {
    @Id
    private Long id;

    public Person() {

    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
```

*src/test/com.myapp/EbeanTest.java*
```java
package com.myapp;

import com.avaje.ebean.Ebean;
import com.avaje.ebean.EbeanServer;
import com.avaje.ebean.EbeanServerFactory;
import com.avaje.ebean.config.ServerConfig;
import models.Person;
import org.junit.Test;

public class EbeanTest {
    @Test
    public void name() throws Exception {
        EbeanServer server = Ebean.getServer("db");
        Person person = new Person();
        server.save(person);
    }
}
```

When I run sbt test I get the following output
```console
java.lang.ExceptionInInitializerError
	at com.sprypoint.beanstalk.EbeanTest.name(EbeanTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalStateException: Bean class models.Person is not enhanced?
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1334)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1079)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1001)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:490)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:217)
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:119)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:142)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:73)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:38)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:54)
	at com.avaje.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:210)
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:168)
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:133)
	at com.avaje.ebean.Ebean.<clinit>(Ebean.java:127)
```

**Comment by woderchen** [comment]
hi buddy
i met same issue before, i fixed.  please check =>  http://ebean-orm.github.io/docs/setup/enhancement

**Comment by ncphillips** [comment]
Ah man, I did not realize I needed that. I usually use ebean in the context of Play, so I was unaware of this plugin.

My bad. Thanks a lot!
